"""add_behavior_pattern_table

Revision ID: 0e3092aff1ba
Revises: e43aee5759fe
Create Date: 2026-06-01 13:57:43.863923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e3092aff1ba'
down_revision: Union[str, Sequence[str], None] = 'e43aee5759fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavior_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('journey', sa.String(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('default_scenarios', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_behavior_pattern_name_version')
    )
    op.create_index(op.f('ix_behavior_patterns_is_active'), 'behavior_patterns', ['is_active'], unique=False)
    op.create_index(op.f('ix_behavior_patterns_journey'), 'behavior_patterns', ['journey'], unique=False)
    op.create_index('ix_behavior_patterns_journey_risk', 'behavior_patterns', ['journey', 'risk_level'], unique=False)
    op.create_index(op.f('ix_behavior_patterns_name'), 'behavior_patterns', ['name'], unique=True)
    op.create_index(op.f('ix_behavior_patterns_risk_level'), 'behavior_patterns', ['risk_level'], unique=False)
    op.create_index(op.f('ix_behavior_patterns_version'), 'behavior_patterns', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_behavior_patterns_version'), table_name='behavior_patterns')
    op.drop_index(op.f('ix_behavior_patterns_risk_level'), table_name='behavior_patterns')
    op.drop_index(op.f('ix_behavior_patterns_name'), table_name='behavior_patterns')
    op.drop_index('ix_behavior_patterns_journey_risk', table_name='behavior_patterns')
    op.drop_index(op.f('ix_behavior_patterns_journey'), table_name='behavior_patterns')
    op.drop_index(op.f('ix_behavior_patterns_is_active'), table_name='behavior_patterns')
    op.drop_table('behavior_patterns')
    # ### end Alembic commands ###
