"""add_behavior_scenario_table

Revision ID: 1de7ae407a96
Revises: c00a6b77841d
Create Date: 2026-06-01 07:33:32.025537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de7ae407a96'
down_revision: Union[str, Sequence[str], None] = 'c00a6b77841d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavior_scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('behavior_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('scenario_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['behavior_id'], ['behaviors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_scenarios_behavior_id'), 'behavior_scenarios', ['behavior_id'], unique=False)
    op.create_index('ix_behavior_scenarios_behavior_priority', 'behavior_scenarios', ['behavior_id', 'priority'], unique=False)
    op.create_index('ix_behavior_scenarios_behavior_type', 'behavior_scenarios', ['behavior_id', 'scenario_type'], unique=False)
    op.create_index(op.f('ix_behavior_scenarios_priority'), 'behavior_scenarios', ['priority'], unique=False)
    op.create_index(op.f('ix_behavior_scenarios_scenario_type'), 'behavior_scenarios', ['scenario_type'], unique=False)
    op.create_index(op.f('ix_behavior_scenarios_status'), 'behavior_scenarios', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_behavior_scenarios_status'), table_name='behavior_scenarios')
    op.drop_index(op.f('ix_behavior_scenarios_scenario_type'), table_name='behavior_scenarios')
    op.drop_index(op.f('ix_behavior_scenarios_priority'), table_name='behavior_scenarios')
    op.drop_index('ix_behavior_scenarios_behavior_type', table_name='behavior_scenarios')
    op.drop_index('ix_behavior_scenarios_behavior_priority', table_name='behavior_scenarios')
    op.drop_index(op.f('ix_behavior_scenarios_behavior_id'), table_name='behavior_scenarios')
    op.drop_table('behavior_scenarios')
    # ### end Alembic commands ###
