"""add_pr_comments

Revision ID: 1e7e70950de3
Revises: ddc80c667eb9
Create Date: 2026-05-23 20:57:49.151463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e7e70950de3'
down_revision: Union[str, Sequence[str], None] = 'ddc80c667eb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pull_request_comment_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('pull_request_id', sa.UUID(), nullable=False),
    sa.Column('github_comment_id', sa.BigInteger(), nullable=True),
    sa.Column('latest_recommendation_run_id', sa.UUID(), nullable=True),
    sa.Column('latest_comment_hash', sa.String(), nullable=True),
    sa.Column('latest_comment_version', sa.String(), nullable=False),
    sa.Column('latest_rendering_rules_version', sa.String(), nullable=False),
    sa.Column('comment_status', sa.String(), nullable=False),
    sa.Column('comment_integrity_status', sa.String(), nullable=False),
    sa.Column('comment_last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_delivery_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_delivery_error', sa.String(), nullable=True),
    sa.Column('next_allowed_delivery_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['latest_recommendation_run_id'], ['recommendation_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'pull_request_id', name='uq_repo_pr_comment_state')
    )
    op.create_index(op.f('ix_pull_request_comment_states_pull_request_id'), 'pull_request_comment_states', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_pull_request_comment_states_repository_id'), 'pull_request_comment_states', ['repository_id'], unique=False)
    op.create_table('pull_request_comment_delivery_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('comment_state_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_run_id', sa.UUID(), nullable=False),
    sa.Column('github_comment_id', sa.BigInteger(), nullable=True),
    sa.Column('delivery_status', sa.String(), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('delivery_latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_state_id'], ['pull_request_comment_states.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_run_id'], ['recommendation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pull_request_comment_delivery_events_comment_state_id'), 'pull_request_comment_delivery_events', ['comment_state_id'], unique=False)
    op.create_index(op.f('ix_pull_request_comment_delivery_events_recommendation_run_id'), 'pull_request_comment_delivery_events', ['recommendation_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pull_request_comment_delivery_events_recommendation_run_id'), table_name='pull_request_comment_delivery_events')
    op.drop_index(op.f('ix_pull_request_comment_delivery_events_comment_state_id'), table_name='pull_request_comment_delivery_events')
    op.drop_table('pull_request_comment_delivery_events')
    op.drop_index(op.f('ix_pull_request_comment_states_repository_id'), table_name='pull_request_comment_states')
    op.drop_index(op.f('ix_pull_request_comment_states_pull_request_id'), table_name='pull_request_comment_states')
    op.drop_table('pull_request_comment_states')
    # ### end Alembic commands ###
