"""make_recommendation_presented_at_nullable

Revision ID: 1fa172047bbf
Revises: f911ba77e9a6
Create Date: 2026-05-24 04:23:02.803461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fa172047bbf'
down_revision: Union[str, Sequence[str], None] = 'f911ba77e9a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rec_eng_feedbacks_outcome_id'), table_name='recommendation_engineer_feedbacks')
    op.create_index(op.f('ix_recommendation_engineer_feedbacks_recommendation_outcome_id'), 'recommendation_engineer_feedbacks', ['recommendation_outcome_id'], unique=False)
    op.alter_column('recommendation_outcomes', 'recommendation_presented_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_recommendation_outcomes_repository_id'), 'recommendation_outcomes', ['repository_id'], unique=False)
    op.drop_index(op.f('ix_rec_test_outcomes_outcome_id'), table_name='recommendation_test_outcomes')
    op.drop_index(op.f('ix_rec_test_outcomes_test_case_id'), table_name='recommendation_test_outcomes')
    op.create_index(op.f('ix_recommendation_test_outcomes_recommendation_outcome_id'), 'recommendation_test_outcomes', ['recommendation_outcome_id'], unique=False)
    op.create_index(op.f('ix_recommendation_test_outcomes_test_case_id'), 'recommendation_test_outcomes', ['test_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_test_outcomes_test_case_id'), table_name='recommendation_test_outcomes')
    op.drop_index(op.f('ix_recommendation_test_outcomes_recommendation_outcome_id'), table_name='recommendation_test_outcomes')
    op.create_index(op.f('ix_rec_test_outcomes_test_case_id'), 'recommendation_test_outcomes', ['test_case_id'], unique=False)
    op.create_index(op.f('ix_rec_test_outcomes_outcome_id'), 'recommendation_test_outcomes', ['recommendation_outcome_id'], unique=False)
    op.drop_index(op.f('ix_recommendation_outcomes_repository_id'), table_name='recommendation_outcomes')
    op.alter_column('recommendation_outcomes', 'recommendation_presented_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_recommendation_engineer_feedbacks_recommendation_outcome_id'), table_name='recommendation_engineer_feedbacks')
    op.create_index(op.f('ix_rec_eng_feedbacks_outcome_id'), 'recommendation_engineer_feedbacks', ['recommendation_outcome_id'], unique=False)
    # ### end Alembic commands ###
