"""add_missing_phase3_recommendation_columns

Revision ID: 2edb9adf92da
Revises: 62268696f788
Create Date: 2026-05-22 22:31:40.292729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2edb9adf92da'
down_revision: Union[str, Sequence[str], None] = '62268696f788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation_input_snapshots', sa.Column('direct_mappings_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('recommendation_input_snapshots', sa.Column('heuristic_mappings_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('recommendation_input_snapshots', sa.Column('ranking_inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.add_column('recommendation_input_snapshots', sa.Column('snapshot_truncated', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('recommendation_input_snapshots', sa.Column('snapshot_size_bytes', sa.Integer(), nullable=True))
    op.add_column('recommendation_reasoning_entries', sa.Column('test_case_id', sa.UUID(), nullable=True))
    op.add_column('recommendation_reasoning_entries', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('recommendation_reasoning_entries', 'source_entity',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('recommendation_reasoning_entries', 'source_reference',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'recommendation_reasoning_entries', 'test_cases', ['test_case_id'], ['id'], ondelete='SET NULL')
    op.add_column('recommendation_runs', sa.Column('recommendation_engine_version', sa.String(), nullable=True))
    op.add_column('recommendation_runs', sa.Column('fallback_policy_version', sa.String(), nullable=True))
    op.add_column('recommendation_runs', sa.Column('dependency_expansion_strategy_version', sa.String(), nullable=True))
    op.add_column('recommendation_runs', sa.Column('pull_request_id', sa.UUID(), nullable=True))
    op.add_column('recommendation_runs', sa.Column('full_suite_runtime_seconds', sa.Float(), nullable=True))
    op.alter_column('recommendation_runs', 'estimated_runtime_seconds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_foreign_key(None, 'recommendation_runs', 'pull_requests', ['pull_request_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recommendation_runs', type_='foreignkey')
    op.alter_column('recommendation_runs', 'estimated_runtime_seconds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('recommendation_runs', 'full_suite_runtime_seconds')
    op.drop_column('recommendation_runs', 'pull_request_id')
    op.drop_column('recommendation_runs', 'dependency_expansion_strategy_version')
    op.drop_column('recommendation_runs', 'fallback_policy_version')
    op.drop_column('recommendation_runs', 'recommendation_engine_version')
    op.drop_constraint(None, 'recommendation_reasoning_entries', type_='foreignkey')
    op.alter_column('recommendation_reasoning_entries', 'source_reference',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('recommendation_reasoning_entries', 'source_entity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('recommendation_reasoning_entries', 'metadata')
    op.drop_column('recommendation_reasoning_entries', 'test_case_id')
    op.drop_column('recommendation_input_snapshots', 'snapshot_size_bytes')
    op.drop_column('recommendation_input_snapshots', 'snapshot_truncated')
    op.drop_column('recommendation_input_snapshots', 'ranking_inputs')
    op.drop_column('recommendation_input_snapshots', 'heuristic_mappings_used')
    op.drop_column('recommendation_input_snapshots', 'direct_mappings_used')
    # ### end Alembic commands ###
