"""add_journey_table

Revision ID: 444f62bebff6
Revises: 1de7ae407a96
Create Date: 2026-06-01 07:36:26.082601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444f62bebff6'
down_revision: Union[str, Sequence[str], None] = '1de7ae407a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journeys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'slug', name='uq_journeys_repo_slug')
    )
    op.create_index(op.f('ix_journeys_repository_id'), 'journeys', ['repository_id'], unique=False)
    op.create_index(op.f('ix_journeys_risk_level'), 'journeys', ['risk_level'], unique=False)
    op.create_index(op.f('ix_journeys_slug'), 'journeys', ['slug'], unique=False)
    op.add_column('behaviors', sa.Column('journey_id', sa.UUID(), nullable=True))
    op.alter_column('behaviors', 'journey_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_behaviors_journey_name'), table_name='behaviors')
    op.drop_index(op.f('ix_behaviors_repo_journey'), table_name='behaviors')
    op.create_index('ix_behaviors_repo_journey', 'behaviors', ['repository_id', 'journey_id'], unique=False)
    op.create_index(op.f('ix_behaviors_journey_id'), 'behaviors', ['journey_id'], unique=False)
    op.create_foreign_key(None, 'behaviors', 'journeys', ['journey_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'behaviors', type_='foreignkey')
    op.drop_index(op.f('ix_behaviors_journey_id'), table_name='behaviors')
    op.drop_index('ix_behaviors_repo_journey', table_name='behaviors')
    op.create_index(op.f('ix_behaviors_repo_journey'), 'behaviors', ['repository_id', 'journey_name'], unique=False)
    op.create_index(op.f('ix_behaviors_journey_name'), 'behaviors', ['journey_name'], unique=False)
    op.alter_column('behaviors', 'journey_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('behaviors', 'journey_id')
    op.drop_index(op.f('ix_journeys_slug'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_risk_level'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_repository_id'), table_name='journeys')
    op.drop_table('journeys')
    # ### end Alembic commands ###
