"""add_github_app_installation

Revision ID: 4752970181af
Revises: 942fa21d1735
Create Date: 2026-05-22 05:11:01.372566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4752970181af'
down_revision: Union[str, Sequence[str], None] = '942fa21d1735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_installations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('github_installation_id', sa.BigInteger(), nullable=False),
    sa.Column('account_login', sa.String(), nullable=False),
    sa.Column('installed_by', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('evidence_health_status', sa.String(), nullable=False),
    sa.Column('active_sync_job_id', sa.UUID(), nullable=True),
    sa.Column('sync_lock_acquired_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_started_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_successful_sync_at', sa.DateTime(), nullable=True),
    sa.Column('consecutive_sync_failures', sa.Integer(), nullable=False),
    sa.Column('last_sync_error', sa.String(), nullable=True),
    sa.Column('last_github_event_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_installations_github_installation_id'), 'github_installations', ['github_installation_id'], unique=True)
    op.create_index(op.f('ix_github_installations_organization_id'), 'github_installations', ['organization_id'], unique=True)
    op.create_table('repository_sync_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('github_installation_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sync_reason', sa.String(), nullable=False),
    sa.Column('evidence_health_status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('total_repositories_seen', sa.Integer(), nullable=False),
    sa.Column('repositories_created', sa.Integer(), nullable=False),
    sa.Column('repositories_updated', sa.Integer(), nullable=False),
    sa.Column('repositories_marked_inactive', sa.Integer(), nullable=False),
    sa.Column('pagination_completed', sa.Boolean(), nullable=False),
    sa.Column('pages_expected', sa.Integer(), nullable=True),
    sa.Column('pages_received', sa.Integer(), nullable=False),
    sa.Column('last_page_url', sa.String(), nullable=True),
    sa.Column('repository_sync_snapshot_artifact_id', sa.UUID(), nullable=True),
    sa.Column('integrity_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_sync_snapshot_artifact_id'], ['raw_artifacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_sync_jobs_evidence_health_status'), 'repository_sync_jobs', ['evidence_health_status'], unique=False)
    op.create_index(op.f('ix_repository_sync_jobs_github_installation_id'), 'repository_sync_jobs', ['github_installation_id'], unique=False)
    op.create_index(op.f('ix_repository_sync_jobs_integrity_status'), 'repository_sync_jobs', ['integrity_status'], unique=False)
    op.create_index(op.f('ix_repository_sync_jobs_organization_id'), 'repository_sync_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_repository_sync_jobs_status'), 'repository_sync_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_repository_sync_jobs_sync_reason'), 'repository_sync_jobs', ['sync_reason'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_delivery_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('installation_id', sa.BigInteger(), nullable=True),
    sa.Column('repository_id', sa.BigInteger(), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('raw_artifact_id', sa.UUID(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['raw_artifact_id'], ['raw_artifacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_action'), 'webhook_events', ['action'], unique=False)
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_github_delivery_id'), 'webhook_events', ['github_delivery_id'], unique=True)
    op.create_index(op.f('ix_webhook_events_installation_id'), 'webhook_events', ['installation_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_processing_status'), 'webhook_events', ['processing_status'], unique=False)
    op.create_index(op.f('ix_webhook_events_repository_id'), 'webhook_events', ['repository_id'], unique=False)
    op.alter_column('raw_artifacts', 'repository_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('repositories', sa.Column('missing_from_github_since', sa.DateTime(), nullable=True))
    op.add_column('repositories', sa.Column('last_seen_in_github_at', sa.DateTime(), nullable=True))
    op.add_column('repositories', sa.Column('deactivation_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'deactivation_reason')
    op.drop_column('repositories', 'last_seen_in_github_at')
    op.drop_column('repositories', 'missing_from_github_since')
    op.alter_column('raw_artifacts', 'repository_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_webhook_events_repository_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_processing_status'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_installation_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_github_delivery_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_action'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_repository_sync_jobs_sync_reason'), table_name='repository_sync_jobs')
    op.drop_index(op.f('ix_repository_sync_jobs_status'), table_name='repository_sync_jobs')
    op.drop_index(op.f('ix_repository_sync_jobs_organization_id'), table_name='repository_sync_jobs')
    op.drop_index(op.f('ix_repository_sync_jobs_integrity_status'), table_name='repository_sync_jobs')
    op.drop_index(op.f('ix_repository_sync_jobs_github_installation_id'), table_name='repository_sync_jobs')
    op.drop_index(op.f('ix_repository_sync_jobs_evidence_health_status'), table_name='repository_sync_jobs')
    op.drop_table('repository_sync_jobs')
    op.drop_index(op.f('ix_github_installations_organization_id'), table_name='github_installations')
    op.drop_index(op.f('ix_github_installations_github_installation_id'), table_name='github_installations')
    op.drop_table('github_installations')
    # ### end Alembic commands ###
