"""add_conservative_recommendation_columns_and_snapshots

Revision ID: 62268696f788
Revises: f147c303de7f
Create Date: 2026-05-22 22:02:43.511667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62268696f788'
down_revision: Union[str, Sequence[str], None] = 'f147c303de7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_input_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_run_id', sa.UUID(), nullable=False),
    sa.Column('changed_files', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dependency_files_expanded', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('coverage_links_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('flaky_profiles_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('historical_failures_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('degradation_rules_triggered', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_run_id'], ['recommendation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_input_snapshots_recommendation_run_id'), 'recommendation_input_snapshots', ['recommendation_run_id'], unique=True)
    op.add_column('recommendation_runs', sa.Column('coverage_report_id', sa.UUID(), nullable=True))
    op.add_column('recommendation_runs', sa.Column('dependency_state_hash', sa.String(), nullable=True))
    op.add_column('recommendation_runs', sa.Column('test_history_window_start', sa.DateTime(), nullable=True))
    op.add_column('recommendation_runs', sa.Column('test_history_window_end', sa.DateTime(), nullable=True))
    op.add_column('recommendation_runs', sa.Column('flakiness_profile_hash', sa.String(), nullable=True))
    op.add_column('recommendation_runs', sa.Column('recommendation_mode', sa.String(), nullable=True))
    op.add_column('recommendation_runs', sa.Column('optimization_allowed', sa.Boolean(), nullable=False))
    op.add_column('recommendation_runs', sa.Column('unsafe_for_optimization', sa.Boolean(), nullable=False))
    op.add_column('recommendation_runs', sa.Column('evidence_quality_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('recommendation_runs', sa.Column('skipped_reason_summary', sa.String(), nullable=True))
    op.add_column('recommendation_runs', sa.Column('skipped_count', sa.Integer(), nullable=False))
    op.add_column('recommendation_runs', sa.Column('top_skipped_examples', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('recommendation_runs', sa.Column('estimated_runtime_seconds', sa.Float(), nullable=True))
    op.add_column('recommendation_runs', sa.Column('runtime_confidence', sa.String(), nullable=True))
    op.add_column('recommendation_runs', sa.Column('runtime_source', sa.String(), nullable=True))
    op.create_foreign_key(None, 'recommendation_runs', 'coverage_reports', ['coverage_report_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recommendation_runs', type_='foreignkey')
    op.drop_column('recommendation_runs', 'runtime_source')
    op.drop_column('recommendation_runs', 'runtime_confidence')
    op.drop_column('recommendation_runs', 'estimated_runtime_seconds')
    op.drop_column('recommendation_runs', 'top_skipped_examples')
    op.drop_column('recommendation_runs', 'skipped_count')
    op.drop_column('recommendation_runs', 'skipped_reason_summary')
    op.drop_column('recommendation_runs', 'evidence_quality_reasons')
    op.drop_column('recommendation_runs', 'unsafe_for_optimization')
    op.drop_column('recommendation_runs', 'optimization_allowed')
    op.drop_column('recommendation_runs', 'recommendation_mode')
    op.drop_column('recommendation_runs', 'flakiness_profile_hash')
    op.drop_column('recommendation_runs', 'test_history_window_end')
    op.drop_column('recommendation_runs', 'test_history_window_start')
    op.drop_column('recommendation_runs', 'dependency_state_hash')
    op.drop_column('recommendation_runs', 'coverage_report_id')
    op.drop_index(op.f('ix_recommendation_input_snapshots_recommendation_run_id'), table_name='recommendation_input_snapshots')
    op.drop_table('recommendation_input_snapshots')
    # ### end Alembic commands ###
