"""Add architecture_edges table for repository graph representation

Revision ID: 62857b73d183
Revises: d9187d4b38db
Create Date: 2026-06-01 22:57:11.323841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62857b73d183'
down_revision: Union[str, Sequence[str], None] = 'd9187d4b38db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('architecture_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('edge_type', sa.Enum('IMPORTS', 'CALLS', 'RENDERS', 'ROUTES_TO', 'USES_MODEL', 'USES_CONFIG', 'TESTS', 'DEPENDS_ON', 'UNKNOWN', name='architecture_edge_type'), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['architecture_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['architecture_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_architecture_edges_edge_type'), 'architecture_edges', ['edge_type'], unique=False)
    op.create_index(op.f('ix_architecture_edges_repository_id'), 'architecture_edges', ['repository_id'], unique=False)
    op.create_index('ix_architecture_edges_source', 'architecture_edges', ['repository_id', 'source_node_id'], unique=False)
    op.create_index(op.f('ix_architecture_edges_source_node_id'), 'architecture_edges', ['source_node_id'], unique=False)
    op.create_index('ix_architecture_edges_target', 'architecture_edges', ['repository_id', 'target_node_id'], unique=False)
    op.create_index(op.f('ix_architecture_edges_target_node_id'), 'architecture_edges', ['target_node_id'], unique=False)
    op.create_index('ix_architecture_edges_unique_directed', 'architecture_edges', ['repository_id', 'source_node_id', 'target_node_id', 'edge_type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_architecture_edges_unique_directed', table_name='architecture_edges')
    op.drop_index(op.f('ix_architecture_edges_target_node_id'), table_name='architecture_edges')
    op.drop_index('ix_architecture_edges_target', table_name='architecture_edges')
    op.drop_index(op.f('ix_architecture_edges_source_node_id'), table_name='architecture_edges')
    op.drop_index('ix_architecture_edges_source', table_name='architecture_edges')
    op.drop_index(op.f('ix_architecture_edges_repository_id'), table_name='architecture_edges')
    op.drop_index(op.f('ix_architecture_edges_edge_type'), table_name='architecture_edges')
    op.drop_table('architecture_edges')
    # ### end Alembic commands ###
