"""add_phase7_pilot_packaging_models

Revision ID: 6589ecbfee06
Revises: 5b8e3f1c9a02
Create Date: 2026-05-24 21:23:56.321965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6589ecbfee06'
down_revision: Union[str, Sequence[str], None] = '5b8e3f1c9a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pilot_organization_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('pilot_name', sa.String(), nullable=False),
    sa.Column('pilot_status', sa.String(), nullable=False),
    sa.Column('pilot_start_date', sa.DateTime(), nullable=False),
    sa.Column('pilot_end_date', sa.DateTime(), nullable=True),
    sa.Column('pricing_model', sa.String(), nullable=False),
    sa.Column('monthly_price_usd', sa.Float(), nullable=True),
    sa.Column('repo_limit', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("pilot_status IN ('ACTIVE', 'COMPLETED', 'CONVERTED', 'EXPIRED')", name='chk_pilot_status'),
    sa.CheckConstraint("pricing_model IN ('FREE', 'FIXED_MONTHLY', 'INTERNAL_DESIGN_PARTNER')", name='chk_pricing_model'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pilot_organization_profiles_organization_id'), 'pilot_organization_profiles', ['organization_id'], unique=True)
    op.create_table('pilot_report_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pilot_profile_id', sa.UUID(), nullable=False),
    sa.Column('report_snapshot_hash', sa.String(), nullable=False),
    sa.Column('report_version', sa.Integer(), nullable=False),
    sa.Column('reporting_window_start', sa.DateTime(), nullable=False),
    sa.Column('reporting_window_end', sa.DateTime(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('report_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pilot_profile_id'], ['pilot_organization_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pilot_report_snapshots_pilot_profile_id'), 'pilot_report_snapshots', ['pilot_profile_id'], unique=False)
    op.create_index(op.f('ix_pilot_report_snapshots_report_snapshot_hash'), 'pilot_report_snapshots', ['report_snapshot_hash'], unique=True)
    op.create_table('pilot_repository_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pilot_profile_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_status', sa.String(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("enrollment_status IN ('ACTIVE', 'REMOVED')", name='chk_enrollment_status'),
    sa.ForeignKeyConstraint(['pilot_profile_id'], ['pilot_organization_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pilot_profile_id', 'repository_id', name='uq_pilot_profile_repository')
    )
    op.create_index(op.f('ix_pilot_repository_enrollments_pilot_profile_id'), 'pilot_repository_enrollments', ['pilot_profile_id'], unique=False)
    op.create_index(op.f('ix_pilot_repository_enrollments_repository_id'), 'pilot_repository_enrollments', ['repository_id'], unique=False)
    op.drop_index(op.f('ix_recommendation_override_records_outcome_id'), table_name='recommendation_override_records')
    op.drop_index(op.f('ix_recommendation_override_records_repo_id'), table_name='recommendation_override_records')
    op.drop_index(op.f('ix_recommendation_override_records_run_id'), table_name='recommendation_override_records')
    op.drop_constraint(op.f('uq_override_records_outcome_id'), 'recommendation_override_records', type_='unique')
    op.create_index(op.f('ix_recommendation_override_records_recommendation_outcome_id'), 'recommendation_override_records', ['recommendation_outcome_id'], unique=True)
    op.create_index(op.f('ix_recommendation_override_records_recommendation_run_id'), 'recommendation_override_records', ['recommendation_run_id'], unique=False)
    op.create_index(op.f('ix_recommendation_override_records_repository_id'), 'recommendation_override_records', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_override_records_repository_id'), table_name='recommendation_override_records')
    op.drop_index(op.f('ix_recommendation_override_records_recommendation_run_id'), table_name='recommendation_override_records')
    op.drop_index(op.f('ix_recommendation_override_records_recommendation_outcome_id'), table_name='recommendation_override_records')
    op.create_unique_constraint(op.f('uq_override_records_outcome_id'), 'recommendation_override_records', ['recommendation_outcome_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_recommendation_override_records_run_id'), 'recommendation_override_records', ['recommendation_run_id'], unique=False)
    op.create_index(op.f('ix_recommendation_override_records_repo_id'), 'recommendation_override_records', ['repository_id'], unique=False)
    op.create_index(op.f('ix_recommendation_override_records_outcome_id'), 'recommendation_override_records', ['recommendation_outcome_id'], unique=True)
    op.drop_index(op.f('ix_pilot_repository_enrollments_repository_id'), table_name='pilot_repository_enrollments')
    op.drop_index(op.f('ix_pilot_repository_enrollments_pilot_profile_id'), table_name='pilot_repository_enrollments')
    op.drop_table('pilot_repository_enrollments')
    op.drop_index(op.f('ix_pilot_report_snapshots_report_snapshot_hash'), table_name='pilot_report_snapshots')
    op.drop_index(op.f('ix_pilot_report_snapshots_pilot_profile_id'), table_name='pilot_report_snapshots')
    op.drop_table('pilot_report_snapshots')
    op.drop_index(op.f('ix_pilot_organization_profiles_organization_id'), table_name='pilot_organization_profiles')
    op.drop_table('pilot_organization_profiles')
    # ### end Alembic commands ###
