"""add_durable_recommendation_storage

Revision ID: 6ad1003e1693
Revises: f0db80fcf4cd
Create Date: 2026-05-28 03:48:37.491589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ad1003e1693'
down_revision: Union[str, Sequence[str], None] = 'f0db80fcf4cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pilot_workspace_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('pilot_name', sa.String(), nullable=False),
    sa.Column('pilot_status', sa.String(), nullable=False),
    sa.Column('pilot_start_date', sa.DateTime(), nullable=False),
    sa.Column('pilot_end_date', sa.DateTime(), nullable=True),
    sa.Column('pricing_model', sa.String(), nullable=False),
    sa.Column('monthly_price_usd', sa.Float(), nullable=True),
    sa.Column('repo_limit', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("pilot_status IN ('ACTIVE', 'COMPLETED', 'CONVERTED', 'EXPIRED')", name='chk_pilot_status'),
    sa.CheckConstraint("pricing_model IN ('FREE', 'FIXED_MONTHLY', 'INTERNAL_DESIGN_PARTNER')", name='chk_pricing_model'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pilot_workspace_profiles_workspace_id'), 'pilot_workspace_profiles', ['workspace_id'], unique=True)
    op.create_table('recommended_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_run_id', sa.UUID(), nullable=False),
    sa.Column('test_identifier', sa.String(), nullable=False),
    sa.Column('test_name', sa.String(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('source_signal', sa.String(), nullable=False),
    sa.Column('estimated_duration_seconds', sa.Float(), nullable=True),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('warning', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_run_id'], ['recommendation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommended_tests_recommendation_run_id'), 'recommended_tests', ['recommendation_run_id'], unique=False)
    op.create_index(op.f('ix_recommended_tests_test_identifier'), 'recommended_tests', ['test_identifier'], unique=False)
    # Drop constraints first using IF EXISTS to avoid dependency errors
    op.execute('ALTER TABLE pilot_report_snapshots DROP CONSTRAINT IF EXISTS fk_pilot_report_snapshots_pilot_profile_id')
    op.execute('ALTER TABLE pilot_report_snapshots DROP CONSTRAINT IF EXISTS pilot_report_snapshots_pilot_profile_id_fkey')
    op.execute('ALTER TABLE pilot_repository_enrollments DROP CONSTRAINT IF EXISTS fk_pilot_repository_enrollments_pilot_profile_id')
    op.execute('ALTER TABLE pilot_repository_enrollments DROP CONSTRAINT IF EXISTS pilot_repository_enrollments_pilot_profile_id_fkey')

    op.drop_index(op.f('ix_pilot_organization_profiles_organization_id'), table_name='pilot_organization_profiles')
    op.drop_table('pilot_organization_profiles')
    op.create_index(op.f('ix_coverage_reports_branch'), 'coverage_reports', ['branch'], unique=False)
    op.alter_column('external_test_case_references', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_external_test_case_references_provider_external_id'), table_name='external_test_case_references')
    op.alter_column('github_installations', 'installation_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('github_installations', 'github_account_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'User'::character varying"))
    op.alter_column('github_installations', 'repository_selection',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'all'::character varying"))
    op.alter_column('github_installations', 'installed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('github_installations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key('fk_pilot_report_snapshots_pilot_profile_id', 'pilot_report_snapshots', 'pilot_workspace_profiles', ['pilot_profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_pilot_repository_enrollments_pilot_profile_id', 'pilot_repository_enrollments', 'pilot_workspace_profiles', ['pilot_profile_id'], ['id'], ondelete='CASCADE')
    op.add_column('recommendation_runs', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.add_column('recommendation_runs', sa.Column('input_snapshot_hash', sa.String(), nullable=True))
    op.add_column('recommendation_runs', sa.Column('recommendation_snapshot_hash', sa.String(), nullable=True))
    op.add_column('recommendation_runs', sa.Column('risk_level', sa.String(), nullable=True))
    op.add_column('recommendation_runs', sa.Column('recommended_tests_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_recommendation_runs_workspace_id'), 'recommendation_runs', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'recommendation_runs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recommendation_runs', type_='foreignkey')
    op.drop_index(op.f('ix_recommendation_runs_workspace_id'), table_name='recommendation_runs')
    op.drop_column('recommendation_runs', 'recommended_tests_count')
    op.drop_column('recommendation_runs', 'risk_level')
    op.drop_column('recommendation_runs', 'recommendation_snapshot_hash')
    op.drop_column('recommendation_runs', 'input_snapshot_hash')
    op.drop_column('recommendation_runs', 'workspace_id')
    op.drop_constraint(None, 'pilot_repository_enrollments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_pilot_repository_enrollments_pilot_profile_id'), 'pilot_repository_enrollments', 'pilot_organization_profiles', ['pilot_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'pilot_report_snapshots', type_='foreignkey')
    op.create_foreign_key(op.f('fk_pilot_report_snapshots_pilot_profile_id'), 'pilot_report_snapshots', 'pilot_organization_profiles', ['pilot_profile_id'], ['id'], ondelete='CASCADE')
    op.alter_column('github_installations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('github_installations', 'installed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('github_installations', 'repository_selection',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'all'::character varying"))
    op.alter_column('github_installations', 'github_account_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'User'::character varying"))
    op.alter_column('github_installations', 'installation_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_index(op.f('ix_external_test_case_references_provider_external_id'), 'external_test_case_references', ['provider', 'external_test_case_id'], unique=False)
    op.alter_column('external_test_case_references', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_coverage_reports_branch'), table_name='coverage_reports')
    op.create_table('pilot_organization_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pilot_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pilot_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pilot_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('pilot_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('pricing_model', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('monthly_price_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('repo_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.CheckConstraint("pilot_status::text = ANY (ARRAY['ACTIVE'::character varying, 'COMPLETED'::character varying, 'CONVERTED'::character varying, 'EXPIRED'::character varying]::text[])", name=op.f('chk_pilot_status')),
    sa.CheckConstraint("pricing_model::text = ANY (ARRAY['FREE'::character varying, 'FIXED_MONTHLY'::character varying, 'INTERNAL_DESIGN_PARTNER'::character varying]::text[])", name=op.f('chk_pricing_model')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('pilot_organization_profiles_organization_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pilot_organization_profiles_pkey'))
    )
    op.create_index(op.f('ix_pilot_organization_profiles_organization_id'), 'pilot_organization_profiles', ['organization_id'], unique=True)
    op.drop_index(op.f('ix_recommended_tests_test_identifier'), table_name='recommended_tests')
    op.drop_index(op.f('ix_recommended_tests_recommendation_run_id'), table_name='recommended_tests')
    op.drop_table('recommended_tests')
    op.drop_index(op.f('ix_pilot_workspace_profiles_workspace_id'), table_name='pilot_workspace_profiles')
    op.drop_table('pilot_workspace_profiles')
    # ### end Alembic commands ###
