"""add_risk_fields_to_behavior

Revision ID: 738169b4af18
Revises: 444f62bebff6
Create Date: 2026-06-01 07:41:42.362242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '738169b4af18'
down_revision: Union[str, Sequence[str], None] = '444f62bebff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('behaviors', sa.Column('risk_reason', sa.Text(), nullable=True))
    op.add_column('behaviors', sa.Column('risk_evidence', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('behaviors', 'risk_evidence')
    op.drop_column('behaviors', 'risk_reason')
    # ### end Alembic commands ###
