"""add_fragility_memory

Revision ID: 7d8b28c4a68b
Revises: 2edb9adf92da
Create Date: 2026-05-23 14:03:31.687926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d8b28c4a68b'
down_revision: Union[str, Sequence[str], None] = '2edb9adf92da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fragility_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('pattern_type', sa.String(), nullable=False),
    sa.Column('normalized_pattern_key', sa.String(), nullable=False),
    sa.Column('fragility_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('confidence_level', sa.String(), nullable=False),
    sa.Column('score_components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fragility_generation_version', sa.String(), nullable=False),
    sa.Column('scoring_formula_version', sa.String(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('incident_count', sa.Integer(), nullable=False),
    sa.Column('related_failure_count', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('invalidated_reason', sa.String(), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(), nullable=True),
    sa.Column('invalidated_by', sa.String(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'normalized_pattern_key', name='uq_repo_pattern_key')
    )
    op.create_index(op.f('ix_fragility_patterns_normalized_pattern_key'), 'fragility_patterns', ['normalized_pattern_key'], unique=False)
    op.create_index(op.f('ix_fragility_patterns_pattern_type'), 'fragility_patterns', ['pattern_type'], unique=False)
    op.create_index(op.f('ix_fragility_patterns_repository_id'), 'fragility_patterns', ['repository_id'], unique=False)
    op.create_table('fragility_evidence_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fragility_pattern_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('source_test_run_id', sa.UUID(), nullable=True),
    sa.Column('source_test_result_id', sa.UUID(), nullable=True),
    sa.Column('source_incident_id', sa.String(), nullable=True),
    sa.Column('source_recommendation_run_id', sa.UUID(), nullable=True),
    sa.Column('source_pull_request_id', sa.UUID(), nullable=True),
    sa.Column('evidence_summary', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fragility_pattern_id'], ['fragility_patterns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_pull_request_id'], ['pull_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_recommendation_run_id'], ['recommendation_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_test_result_id'], ['test_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_test_run_id'], ['test_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fragility_evidence_links_fragility_pattern_id'), 'fragility_evidence_links', ['fragility_pattern_id'], unique=False)
    op.create_table('fragility_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_run_id', sa.UUID(), nullable=True),
    sa.Column('generation_trigger', sa.String(), nullable=False),
    sa.Column('active_pattern_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pattern_hashes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_version', sa.String(), nullable=False),
    sa.Column('scoring_version', sa.String(), nullable=False),
    sa.Column('evidence_window', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_run_id'], ['recommendation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fragility_snapshots_recommendation_run_id'), 'fragility_snapshots', ['recommendation_run_id'], unique=False)
    op.create_index(op.f('ix_fragility_snapshots_repository_id'), 'fragility_snapshots', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fragility_snapshots_repository_id'), table_name='fragility_snapshots')
    op.drop_index(op.f('ix_fragility_snapshots_recommendation_run_id'), table_name='fragility_snapshots')
    op.drop_table('fragility_snapshots')
    op.drop_index(op.f('ix_fragility_evidence_links_fragility_pattern_id'), table_name='fragility_evidence_links')
    op.drop_table('fragility_evidence_links')
    op.drop_index(op.f('ix_fragility_patterns_repository_id'), table_name='fragility_patterns')
    op.drop_index(op.f('ix_fragility_patterns_pattern_type'), table_name='fragility_patterns')
    op.drop_index(op.f('ix_fragility_patterns_normalized_pattern_key'), table_name='fragility_patterns')
    op.drop_table('fragility_patterns')
    # ### end Alembic commands ###
