"""add_behavior_table

Revision ID: 834f57a4d970
Revises: 6d65c61952cc
Create Date: 2026-06-01 07:27:44.474338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '834f57a4d970'
down_revision: Union[str, Sequence[str], None] = '6d65c61952cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behaviors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('journey_name', sa.String(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('discovery_source', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'slug', name='uq_behaviors_repo_slug')
    )
    op.create_index(op.f('ix_behaviors_discovery_source'), 'behaviors', ['discovery_source'], unique=False)
    op.create_index(op.f('ix_behaviors_journey_name'), 'behaviors', ['journey_name'], unique=False)
    op.create_index('ix_behaviors_repo_journey', 'behaviors', ['repository_id', 'journey_name'], unique=False)
    op.create_index('ix_behaviors_repo_status', 'behaviors', ['repository_id', 'status'], unique=False)
    op.create_index(op.f('ix_behaviors_repository_id'), 'behaviors', ['repository_id'], unique=False)
    op.create_index(op.f('ix_behaviors_risk_level'), 'behaviors', ['risk_level'], unique=False)
    op.create_index(op.f('ix_behaviors_slug'), 'behaviors', ['slug'], unique=False)
    op.create_index(op.f('ix_behaviors_status'), 'behaviors', ['status'], unique=False)
    op.drop_index(op.f('ix_scenario_intents_canonical_key'), table_name='scenario_intents')
    op.create_index(op.f('ix_scenario_intents_canonical_key'), 'scenario_intents', ['canonical_key'], unique=True)
    op.create_index(op.f('ix_scenario_intents_behavior'), 'scenario_intents', ['behavior'], unique=False)
    op.create_index(op.f('ix_scenario_intents_case_type'), 'scenario_intents', ['case_type'], unique=False)
    op.create_index(op.f('ix_scenario_intents_domain'), 'scenario_intents', ['domain'], unique=False)
    op.create_index(op.f('ix_scenario_intents_feature'), 'scenario_intents', ['feature'], unique=False)
    op.create_index(op.f('ix_scenario_intents_layer'), 'scenario_intents', ['layer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_intents_layer'), table_name='scenario_intents')
    op.drop_index(op.f('ix_scenario_intents_feature'), table_name='scenario_intents')
    op.drop_index(op.f('ix_scenario_intents_domain'), table_name='scenario_intents')
    op.drop_index(op.f('ix_scenario_intents_case_type'), table_name='scenario_intents')
    op.drop_index(op.f('ix_scenario_intents_behavior'), table_name='scenario_intents')
    op.drop_index(op.f('ix_scenario_intents_canonical_key'), table_name='scenario_intents')
    op.create_index(op.f('ix_scenario_intents_canonical_key'), 'scenario_intents', ['canonical_key'], unique=False)
    op.drop_index(op.f('ix_behaviors_status'), table_name='behaviors')
    op.drop_index(op.f('ix_behaviors_slug'), table_name='behaviors')
    op.drop_index(op.f('ix_behaviors_risk_level'), table_name='behaviors')
    op.drop_index(op.f('ix_behaviors_repository_id'), table_name='behaviors')
    op.drop_index('ix_behaviors_repo_status', table_name='behaviors')
    op.drop_index('ix_behaviors_repo_journey', table_name='behaviors')
    op.drop_index(op.f('ix_behaviors_journey_name'), table_name='behaviors')
    op.drop_index(op.f('ix_behaviors_discovery_source'), table_name='behaviors')
    op.drop_table('behaviors')
    # ### end Alembic commands ###
