"""add_suggested_test_scenarios

Revision ID: 8fa3e00ec72e
Revises: ff27f7249c76
Create Date: 2026-05-31 02:32:30.766741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fa3e00ec72e'
down_revision: Union[str, Sequence[str], None] = 'ff27f7249c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggested_test_scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_run_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('testing_type', sa.String(), nullable=False),
    sa.Column('impacted_area', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('preconditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('test_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_result', sa.String(), nullable=False),
    sa.Column('automation_candidate', sa.Boolean(), nullable=False),
    sa.Column('related_changed_files', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('source_signal', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_run_id'], ['recommendation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggested_test_scenarios_recommendation_run_id'), 'suggested_test_scenarios', ['recommendation_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suggested_test_scenarios_recommendation_run_id'), table_name='suggested_test_scenarios')
    op.drop_table('suggested_test_scenarios')
    # ### end Alembic commands ###
