"""Initial Phase 2 schema

Revision ID: 942fa21d1735
Revises: 
Create Date: 2026-05-22 04:10:57.597382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '942fa21d1735'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('system_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_events_entity_id'), 'system_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_system_events_entity_type'), 'system_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_system_events_event_type'), 'system_events', ['event_type'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('github_repo_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_github_repo_id'), 'repositories', ['github_repo_id'], unique=True)
    op.create_index(op.f('ix_repositories_organization_id'), 'repositories', ['organization_id'], unique=False)
    op.create_table('file_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('depends_on_file_path', sa.String(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_dependencies_commit_sha'), 'file_dependencies', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_file_dependencies_depends_on_file_path'), 'file_dependencies', ['depends_on_file_path'], unique=False)
    op.create_index(op.f('ix_file_dependencies_file_path'), 'file_dependencies', ['file_path'], unique=False)
    op.create_index(op.f('ix_file_dependencies_repository_id'), 'file_dependencies', ['repository_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_job_type'), 'ingestion_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_repository_id'), 'ingestion_jobs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_status'), 'ingestion_jobs', ['status'], unique=False)
    op.create_table('raw_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.String(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('artifact_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_artifacts_artifact_type'), 'raw_artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_raw_artifacts_repository_id'), 'raw_artifacts', ['repository_id'], unique=False)
    op.create_table('recommendation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('pr_id', sa.String(), nullable=False),
    sa.Column('triggered_by', sa.String(), nullable=False),
    sa.Column('evidence_quality', sa.String(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('ruleset_version', sa.String(), nullable=False),
    sa.Column('degradation_policy_version', sa.String(), nullable=False),
    sa.Column('recommendation_reasoning_summary', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_runs_pr_id'), 'recommendation_runs', ['pr_id'], unique=False)
    op.create_index(op.f('ix_recommendation_runs_repository_id'), 'recommendation_runs', ['repository_id'], unique=False)
    op.create_table('recommendation_outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_run_id', sa.UUID(), nullable=False),
    sa.Column('executed_tests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manually_added_tests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manually_removed_tests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('was_followed', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.String(), nullable=True),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('rollback_occurred', sa.Boolean(), nullable=False),
    sa.Column('escaped_defect', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_run_id'], ['recommendation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_outcomes_recommendation_run_id'), 'recommendation_outcomes', ['recommendation_run_id'], unique=True)
    op.create_table('recommendation_reasoning_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_run_id', sa.UUID(), nullable=False),
    sa.Column('reason_type', sa.String(), nullable=False),
    sa.Column('source_entity', sa.String(), nullable=False),
    sa.Column('source_reference', sa.String(), nullable=False),
    sa.Column('human_readable_reason', sa.String(), nullable=False),
    sa.Column('confidence_level', sa.String(), nullable=False),
    sa.Column('evidence_priority', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_run_id'], ['recommendation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_reasoning_entries_recommendation_run_id'), 'recommendation_reasoning_entries', ['recommendation_run_id'], unique=False)
    op.create_table('recommendation_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_run_id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.String(), nullable=False),
    sa.Column('reason_type', sa.String(), nullable=False),
    sa.Column('reason_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_run_id'], ['recommendation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_tests_recommendation_run_id'), 'recommendation_tests', ['recommendation_run_id'], unique=False)
    op.create_index(op.f('ix_recommendation_tests_test_case_id'), 'recommendation_tests', ['test_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_tests_test_case_id'), table_name='recommendation_tests')
    op.drop_index(op.f('ix_recommendation_tests_recommendation_run_id'), table_name='recommendation_tests')
    op.drop_table('recommendation_tests')
    op.drop_index(op.f('ix_recommendation_reasoning_entries_recommendation_run_id'), table_name='recommendation_reasoning_entries')
    op.drop_table('recommendation_reasoning_entries')
    op.drop_index(op.f('ix_recommendation_outcomes_recommendation_run_id'), table_name='recommendation_outcomes')
    op.drop_table('recommendation_outcomes')
    op.drop_index(op.f('ix_recommendation_runs_repository_id'), table_name='recommendation_runs')
    op.drop_index(op.f('ix_recommendation_runs_pr_id'), table_name='recommendation_runs')
    op.drop_table('recommendation_runs')
    op.drop_index(op.f('ix_raw_artifacts_repository_id'), table_name='raw_artifacts')
    op.drop_index(op.f('ix_raw_artifacts_artifact_type'), table_name='raw_artifacts')
    op.drop_table('raw_artifacts')
    op.drop_index(op.f('ix_ingestion_jobs_status'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_repository_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_job_type'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_file_dependencies_repository_id'), table_name='file_dependencies')
    op.drop_index(op.f('ix_file_dependencies_file_path'), table_name='file_dependencies')
    op.drop_index(op.f('ix_file_dependencies_depends_on_file_path'), table_name='file_dependencies')
    op.drop_index(op.f('ix_file_dependencies_commit_sha'), table_name='file_dependencies')
    op.drop_table('file_dependencies')
    op.drop_index(op.f('ix_repositories_organization_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_github_repo_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_system_events_event_type'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_entity_type'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_entity_id'), table_name='system_events')
    op.drop_table('system_events')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
