"""add_junit_ingestion

Revision ID: 963246bf6f44
Revises: a4a923036304
Create Date: 2026-05-22 06:29:09.232976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '963246bf6f44'
down_revision: Union[str, Sequence[str], None] = 'a4a923036304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('suite_name', sa.String(), nullable=False),
    sa.Column('test_name', sa.String(), nullable=False),
    sa.Column('stable_identity', sa.String(), nullable=False),
    sa.Column('raw_test_name', sa.String(), nullable=True),
    sa.Column('normalized_test_name', sa.String(), nullable=True),
    sa.Column('normalized_identity_strategy', sa.String(), nullable=True),
    sa.Column('framework_name', sa.String(), nullable=True),
    sa.Column('framework_version', sa.String(), nullable=True),
    sa.Column('identity_normalization_version', sa.Integer(), nullable=True),
    sa.Column('canonical_identity_hash', sa.String(), nullable=False),
    sa.Column('previous_identity_hash', sa.String(), nullable=True),
    sa.Column('identity_lineage_root_hash', sa.String(), nullable=False),
    sa.Column('identity_version', sa.Integer(), nullable=False),
    sa.Column('identity_resolution_strategy', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'canonical_identity_hash', name='uq_test_cases_repo_canonical_hash')
    )
    op.create_index(op.f('ix_test_cases_canonical_identity_hash'), 'test_cases', ['canonical_identity_hash'], unique=False)
    op.create_index(op.f('ix_test_cases_identity_lineage_root_hash'), 'test_cases', ['identity_lineage_root_hash'], unique=False)
    op.create_index(op.f('ix_test_cases_previous_identity_hash'), 'test_cases', ['previous_identity_hash'], unique=False)
    op.create_index('ix_test_cases_repo_stable_identity', 'test_cases', ['repository_id', 'stable_identity'], unique=False)
    op.create_index(op.f('ix_test_cases_repository_id'), 'test_cases', ['repository_id'], unique=False)
    op.create_table('test_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('pull_request_id', sa.UUID(), nullable=True),
    sa.Column('raw_artifact_id', sa.UUID(), nullable=True),
    sa.Column('parent_test_run_id', sa.UUID(), nullable=True),
    sa.Column('ingestion_reason', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('source_correlation_id', sa.String(), nullable=True),
    sa.Column('request_origin', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('normalized_execution_fingerprint', sa.String(), nullable=False),
    sa.Column('parser_version', sa.String(), nullable=False),
    sa.Column('parser_support_status', sa.String(), nullable=True),
    sa.Column('normalization_schema_version', sa.String(), nullable=False),
    sa.Column('replay_verification_status', sa.String(), nullable=True),
    sa.Column('replay_verified_at', sa.DateTime(), nullable=True),
    sa.Column('replay_audit_count', sa.Integer(), nullable=True),
    sa.Column('last_replay_audit_at', sa.DateTime(), nullable=True),
    sa.Column('replay_drift_detected', sa.Boolean(), nullable=False),
    sa.Column('retention_class', sa.String(), nullable=True),
    sa.Column('archival_status', sa.String(), nullable=True),
    sa.Column('retention_locked', sa.Boolean(), nullable=False),
    sa.Column('retention_lock_reason', sa.String(), nullable=True),
    sa.Column('recommendation_eligibility_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendation_replay_eligible', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('evidence_health_status', sa.String(), nullable=False),
    sa.Column('consistency_status', sa.String(), nullable=False),
    sa.Column('consistency_severity', sa.String(), nullable=False),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('passed_tests', sa.Integer(), nullable=False),
    sa.Column('failed_tests', sa.Integer(), nullable=False),
    sa.Column('skipped_tests', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('queue_wait_duration_ms', sa.Integer(), nullable=True),
    sa.Column('ingestion_retry_count', sa.Integer(), nullable=True),
    sa.Column('ingestion_backpressure_applied', sa.Boolean(), nullable=False),
    sa.Column('ingestion_diagnostics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('consistency_diagnostics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diagnostics_truncated', sa.Boolean(), nullable=False),
    sa.Column('execution_sequence_number', sa.Integer(), nullable=True),
    sa.Column('execution_window_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_test_run_id'], ['test_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_artifact_id'], ['raw_artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'normalized_execution_fingerprint', name='uq_test_runs_repo_execution_fingerprint')
    )
    op.create_index(op.f('ix_test_runs_commit_sha'), 'test_runs', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_test_runs_correlation_id'), 'test_runs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_test_runs_file_hash'), 'test_runs', ['file_hash'], unique=False)
    op.create_index(op.f('ix_test_runs_normalized_execution_fingerprint'), 'test_runs', ['normalized_execution_fingerprint'], unique=False)
    op.create_index(op.f('ix_test_runs_pull_request_id'), 'test_runs', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_test_runs_repository_id'), 'test_runs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_test_runs_source_correlation_id'), 'test_runs', ['source_correlation_id'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_run_id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('failure_message', sa.String(), nullable=True),
    sa.Column('stack_trace', sa.String(), nullable=True),
    sa.Column('stack_trace_redaction_status', sa.String(), nullable=True),
    sa.Column('redaction_version', sa.String(), nullable=True),
    sa.Column('contains_pii', sa.Boolean(), nullable=True),
    sa.Column('contains_secrets', sa.Boolean(), nullable=True),
    sa.Column('compliance_classification', sa.String(), nullable=True),
    sa.Column('encryption_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_results_test_case_id'), 'test_results', ['test_case_id'], unique=False)
    op.create_index(op.f('ix_test_results_test_run_id'), 'test_results', ['test_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_results_test_run_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_test_case_id'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_test_runs_source_correlation_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_repository_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_pull_request_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_normalized_execution_fingerprint'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_file_hash'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_correlation_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_commit_sha'), table_name='test_runs')
    op.drop_table('test_runs')
    op.drop_index(op.f('ix_test_cases_repository_id'), table_name='test_cases')
    op.drop_index('ix_test_cases_repo_stable_identity', table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_previous_identity_hash'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_identity_lineage_root_hash'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_canonical_identity_hash'), table_name='test_cases')
    op.drop_table('test_cases')
    # ### end Alembic commands ###
