"""add_project_context_indices_table

Revision ID: 9ac3ae02d250
Revises: 8fa3e00ec72e
Create Date: 2026-05-31 19:35:51.028508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ac3ae02d250'
down_revision: Union[str, Sequence[str], None] = '8fa3e00ec72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_context_indices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('detected_frameworks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('routes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('api_endpoints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('modules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('domains', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_journeys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('test_assets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('security_sensitive_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_context_indices_repository_id'), 'project_context_indices', ['repository_id'], unique=False)
    op.drop_index(op.f('ix_defect_learning_events_outcome_id'), table_name='defect_learning_events')
    op.drop_index(op.f('ix_defect_learning_events_pull_request_id'), table_name='defect_learning_events')
    op.drop_index(op.f('ix_defect_learning_events_repo_created_at'), table_name='defect_learning_events')
    op.drop_index(op.f('ix_defect_learning_events_repository_id'), table_name='defect_learning_events')
    op.drop_table('defect_learning_events')
    op.drop_index(op.f('ix_pattern_learning_repo_pattern'), table_name='pattern_learnings')
    op.drop_index(op.f('ix_pattern_learning_repo_test'), table_name='pattern_learnings')
    op.drop_index(op.f('ix_pattern_learnings_pattern_key'), table_name='pattern_learnings')
    op.drop_index(op.f('ix_pattern_learnings_repository_id'), table_name='pattern_learnings')
    op.drop_index(op.f('ix_pattern_learnings_test_identifier'), table_name='pattern_learnings')
    op.drop_table('pattern_learnings')
    op.alter_column('test_coverage_links', 'override_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of times an engineer manually added this test (source=MANUAL_OVERRIDE upserts only). Distinct from run_count which counts all sources.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('test_coverage_links', 'defect_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of times a production defect escaped while this test was NOT executed for this file (ESCAPED_DEFECT source only). Distinct from run_count and override_count.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_test_coverage_links_repository_id'), table_name='test_coverage_links')
    op.drop_index(op.f('ix_test_coverage_links_workspace_id'), table_name='test_coverage_links')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_test_coverage_links_workspace_id'), 'test_coverage_links', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_test_coverage_links_repository_id'), 'test_coverage_links', ['repository_id'], unique=False)
    op.alter_column('test_coverage_links', 'defect_count',
               existing_type=sa.INTEGER(),
               comment='Number of times a production defect escaped while this test was NOT executed for this file (ESCAPED_DEFECT source only). Distinct from run_count and override_count.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('test_coverage_links', 'override_count',
               existing_type=sa.INTEGER(),
               comment='Number of times an engineer manually added this test (source=MANUAL_OVERRIDE upserts only). Distinct from run_count which counts all sources.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.create_table('pattern_learnings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('repository_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pattern_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('test_identifier', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source', postgresql.ENUM('ESCAPED_DEFECT', 'MANUAL_OVERRIDE', 'FOLLOWED', 'HEURISTIC', name='pattern_learning_source'), autoincrement=False, nullable=False),
    sa.Column('strength', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_outcome_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name=op.f('chk_pattern_learning_confidence')),
    sa.CheckConstraint('strength >= 0.0 AND strength <= 1.0', name=op.f('chk_pattern_learning_strength')),
    sa.ForeignKeyConstraint(['last_outcome_id'], ['recommendation_outcomes.id'], name=op.f('pattern_learnings_last_outcome_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('pattern_learnings_repository_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pattern_learnings_pkey')),
    sa.UniqueConstraint('repository_id', 'pattern_key', 'test_identifier', 'source', name=op.f('uq_pattern_learning_repo_pattern_test_source'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_pattern_learnings_test_identifier'), 'pattern_learnings', ['test_identifier'], unique=False)
    op.create_index(op.f('ix_pattern_learnings_repository_id'), 'pattern_learnings', ['repository_id'], unique=False)
    op.create_index(op.f('ix_pattern_learnings_pattern_key'), 'pattern_learnings', ['pattern_key'], unique=False)
    op.create_index(op.f('ix_pattern_learning_repo_test'), 'pattern_learnings', ['repository_id', 'test_identifier'], unique=False)
    op.create_index(op.f('ix_pattern_learning_repo_pattern'), 'pattern_learnings', ['repository_id', 'pattern_key'], unique=False)
    op.create_table('defect_learning_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('repository_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('recommendation_outcome_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pull_request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('trigger_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('changed_files', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('recommended_tests', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('executed_tests', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('missed_tests', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('links_created', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('links_strengthened', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('defect_count_at_time', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], name=op.f('defect_learning_events_pull_request_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommendation_outcome_id'], ['recommendation_outcomes.id'], name=op.f('defect_learning_events_recommendation_outcome_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('defect_learning_events_repository_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('defect_learning_events_pkey'))
    )
    op.create_index(op.f('ix_defect_learning_events_repository_id'), 'defect_learning_events', ['repository_id'], unique=False)
    op.create_index(op.f('ix_defect_learning_events_repo_created_at'), 'defect_learning_events', ['repository_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_defect_learning_events_pull_request_id'), 'defect_learning_events', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_defect_learning_events_outcome_id'), 'defect_learning_events', ['recommendation_outcome_id'], unique=False)
    op.drop_index(op.f('ix_project_context_indices_repository_id'), table_name='project_context_indices')
    op.drop_table('project_context_indices')
    # ### end Alembic commands ###
