"""add_lcov_coverage

Revision ID: 9da8a3ea539f
Revises: 963246bf6f44
Create Date: 2026-05-22 06:52:13.338534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9da8a3ea539f'
down_revision: Union[str, Sequence[str], None] = '963246bf6f44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coverage_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=False),
    sa.Column('pull_request_id', sa.UUID(), nullable=True),
    sa.Column('raw_artifact_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('overall_coverage_pct', sa.Float(), nullable=False),
    sa.Column('total_lines', sa.Integer(), nullable=False),
    sa.Column('covered_lines_count', sa.Integer(), nullable=False),
    sa.Column('uncovered_lines_count', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.String(), nullable=False),
    sa.Column('confidence_logic', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_artifact_id'], ['raw_artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coverage_reports_commit_sha'), 'coverage_reports', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_coverage_reports_correlation_id'), 'coverage_reports', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_coverage_reports_file_hash'), 'coverage_reports', ['file_hash'], unique=False)
    op.create_index(op.f('ix_coverage_reports_pull_request_id'), 'coverage_reports', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_coverage_reports_repository_id'), 'coverage_reports', ['repository_id'], unique=False)
    op.create_table('coverage_file_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coverage_report_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('covered_lines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uncovered_lines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_lines_count', sa.Integer(), nullable=False),
    sa.Column('covered_lines_count', sa.Integer(), nullable=False),
    sa.Column('uncovered_lines_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coverage_report_id'], ['coverage_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coverage_report_id', 'file_path', name='uq_coverage_file_entries_report_path')
    )
    op.create_index(op.f('ix_coverage_file_entries_coverage_report_id'), 'coverage_file_entries', ['coverage_report_id'], unique=False)
    op.create_index(op.f('ix_coverage_file_entries_file_path'), 'coverage_file_entries', ['file_path'], unique=False)
    op.create_table('file_test_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coverage_report_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('test_case_id', sa.UUID(), nullable=False),
    sa.Column('mapping_type', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coverage_report_id'], ['coverage_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coverage_report_id', 'file_path', 'test_case_id', name='uq_file_test_links_report_file_test')
    )
    op.create_index(op.f('ix_file_test_links_coverage_report_id'), 'file_test_links', ['coverage_report_id'], unique=False)
    op.create_index(op.f('ix_file_test_links_file_path'), 'file_test_links', ['file_path'], unique=False)
    op.create_index(op.f('ix_file_test_links_test_case_id'), 'file_test_links', ['test_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_test_links_test_case_id'), table_name='file_test_links')
    op.drop_index(op.f('ix_file_test_links_file_path'), table_name='file_test_links')
    op.drop_index(op.f('ix_file_test_links_coverage_report_id'), table_name='file_test_links')
    op.drop_table('file_test_links')
    op.drop_index(op.f('ix_coverage_file_entries_file_path'), table_name='coverage_file_entries')
    op.drop_index(op.f('ix_coverage_file_entries_coverage_report_id'), table_name='coverage_file_entries')
    op.drop_table('coverage_file_entries')
    op.drop_index(op.f('ix_coverage_reports_repository_id'), table_name='coverage_reports')
    op.drop_index(op.f('ix_coverage_reports_pull_request_id'), table_name='coverage_reports')
    op.drop_index(op.f('ix_coverage_reports_file_hash'), table_name='coverage_reports')
    op.drop_index(op.f('ix_coverage_reports_correlation_id'), table_name='coverage_reports')
    op.drop_index(op.f('ix_coverage_reports_commit_sha'), table_name='coverage_reports')
    op.drop_table('coverage_reports')
    # ### end Alembic commands ###
