"""add_journey_business_value_status_soft_delete

Revision ID: a1b2c3d4e5f8
Revises: 444f62bebff6
Create Date: 2026-06-01 14:32:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f8'
down_revision: Union[str, Sequence[str], None] = '444f62bebff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journeys', sa.Column('business_value', sa.Text(), nullable=True))
    op.add_column('journeys', sa.Column('status', sa.String(), nullable=False, server_default='DISCOVERED'))
    op.add_column('journeys', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    
    # Create indexes for new fields
    op.create_index(op.f('ix_journeys_status'), 'journeys', ['status'], unique=False)
    op.create_index(op.f('ix_journeys_is_deleted'), 'journeys', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journeys_is_deleted'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_status'), table_name='journeys')
    op.drop_column('journeys', 'is_deleted')
    op.drop_column('journeys', 'status')
    op.drop_column('journeys', 'business_value')
    # ### end Alembic commands ###
