"""add_scenario_intent_table

Revision ID: a1b2c3d4e5f7
Revises: 8fa3e00ec72e
Create Date: 2026-06-01 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f7'
down_revision: Union[str, Sequence[str], None] = '8fa3e00ec72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create scenario_intents table
    op.create_table('scenario_intents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_run_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('behavior', sa.String(), nullable=False),
    sa.Column('layer', sa.String(), nullable=False),
    sa.Column('case_type', sa.String(), nullable=False),
    sa.Column('canonical_key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('risk_category', sa.String(), nullable=False),
    sa.Column('related_changed_files', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_run_id'], ['recommendation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_intents_recommendation_run_id'), 'scenario_intents', ['recommendation_run_id'], unique=False)
    op.create_index(op.f('ix_scenario_intents_canonical_key'), 'scenario_intents', ['canonical_key'], unique=False)
    
    # Add scenario_intent_id column to recommendation_tests table
    op.add_column('recommendation_tests',
    sa.Column('scenario_intent_id', sa.UUID(), nullable=True)
    )
    op.create_foreign_key('fk_recommendation_tests_scenario_intent_id', 'recommendation_tests', 'scenario_intents', ['scenario_intent_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_recommendation_tests_scenario_intent_id'), 'recommendation_tests', ['scenario_intent_id'], unique=False)
    
    # Add scenario_intent_id column to suggested_test_scenarios table
    op.add_column('suggested_test_scenarios',
    sa.Column('scenario_intent_id', sa.UUID(), nullable=True)
    )
    op.create_foreign_key('fk_suggested_test_scenarios_scenario_intent_id', 'suggested_test_scenarios', 'scenario_intents', ['scenario_intent_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_suggested_test_scenarios_scenario_intent_id'), 'suggested_test_scenarios', ['scenario_intent_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop foreign keys and indexes from suggested_test_scenarios
    op.drop_index(op.f('ix_suggested_test_scenarios_scenario_intent_id'), table_name='suggested_test_scenarios')
    op.drop_constraint('fk_suggested_test_scenarios_scenario_intent_id', 'suggested_test_scenarios', type_='foreignkey')
    op.drop_column('suggested_test_scenarios', 'scenario_intent_id')
    
    # Drop foreign keys and indexes from recommendation_tests
    op.drop_index(op.f('ix_recommendation_tests_scenario_intent_id'), table_name='recommendation_tests')
    op.drop_constraint('fk_recommendation_tests_scenario_intent_id', 'recommendation_tests', type_='foreignkey')
    op.drop_column('recommendation_tests', 'scenario_intent_id')
    
    # Drop scenario_intents table
    op.drop_index(op.f('ix_scenario_intents_canonical_key'), table_name='scenario_intents')
    op.drop_index(op.f('ix_scenario_intents_recommendation_run_id'), table_name='scenario_intents')
    op.drop_table('scenario_intents')
    
    # ### end Alembic commands ###
