"""add_repository_ci_cd_policies

Revision ID: a1b2c3d4e5f9
Revises: d00767b45df8
Create Date: 2026-06-18 05:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f9'
down_revision: Union[str, Sequence[str], None] = 'd00767b45df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_ci_cd_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('required_check_name', sa.String(length=255), nullable=False),
    sa.Column('ci_fail_on_partial', sa.Boolean(), nullable=False),
    sa.Column('fail_on_unknown_gate', sa.Boolean(), nullable=False),
    sa.Column('fail_on_missing_recommendation', sa.Boolean(), nullable=False),
    sa.Column('require_artifact', sa.Boolean(), nullable=False),
    sa.Column('require_pr_comment', sa.Boolean(), nullable=False),
    sa.Column('allow_manual_override', sa.Boolean(), nullable=False),
    sa.Column('manual_override_requires_reason', sa.Boolean(), nullable=False),
    sa.Column('strict_mode', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id')
    )
    op.create_index(op.f('ix_repository_ci_cd_policies_repository_id'), 'repository_ci_cd_policies', ['repository_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repository_ci_cd_policies_repository_id'), table_name='repository_ci_cd_policies')
    op.drop_table('repository_ci_cd_policies')
    # ### end Alembic commands ###
