"""add_pull_requests_and_provenance

Revision ID: a4a923036304
Revises: 4752970181af
Create Date: 2026-05-22 05:41:26.280270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4a923036304'
down_revision: Union[str, Sequence[str], None] = '4752970181af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pull_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('github_pr_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('source_branch', sa.String(), nullable=False),
    sa.Column('target_branch', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('changed_files_count', sa.Integer(), nullable=False),
    sa.Column('head_commit_sha', sa.String(), nullable=False),
    sa.Column('merged', sa.Boolean(), nullable=False),
    sa.Column('merged_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('github_created_at', sa.DateTime(), nullable=False),
    sa.Column('github_updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('sync_integrity_status', sa.String(), nullable=False),
    sa.Column('evidence_health_status', sa.String(), nullable=False),
    sa.Column('evidence_consistency_status', sa.String(), nullable=False),
    sa.Column('last_sync_started_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_successful_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_error', sa.String(), nullable=True),
    sa.Column('active_sync_job_id', sa.UUID(), nullable=True),
    sa.Column('evidence_truncated', sa.Boolean(), nullable=False),
    sa.Column('truncation_reason', sa.String(), nullable=True),
    sa.Column('unsafe_for_optimization', sa.Boolean(), nullable=False),
    sa.Column('last_github_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_processed_delivery_id', sa.String(), nullable=True),
    sa.Column('reconciliation_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pull_requests_github_pr_id'), 'pull_requests', ['github_pr_id'], unique=True)
    op.create_index(op.f('ix_pull_requests_repository_id'), 'pull_requests', ['repository_id'], unique=False)
    op.create_table('pull_request_changed_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pull_request_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('previous_filename', sa.String(), nullable=True),
    sa.Column('patch_summary', sa.String(), nullable=True),
    sa.Column('file_sha', sa.String(), nullable=True),
    sa.Column('patch_hash', sa.String(), nullable=True),
    sa.Column('patch_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pull_request_changed_files_file_path'), 'pull_request_changed_files', ['file_path'], unique=False)
    op.create_index(op.f('ix_pull_request_changed_files_pull_request_id'), 'pull_request_changed_files', ['pull_request_id'], unique=False)
    op.create_table('pull_request_commits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pull_request_id', sa.UUID(), nullable=False),
    sa.Column('sha', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('author_email', sa.String(), nullable=True),
    sa.Column('commit_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pull_request_commits_pull_request_id'), 'pull_request_commits', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_pull_request_commits_sha'), 'pull_request_commits', ['sha'], unique=False)
    op.create_table('pull_request_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pull_request_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('head_commit_sha', sa.String(), nullable=False),
    sa.Column('github_pr_updated_at', sa.DateTime(), nullable=False),
    sa.Column('snapshot_reason', sa.String(), nullable=False),
    sa.Column('snapshot_schema_version', sa.String(), nullable=False),
    sa.Column('normalization_engine_version', sa.String(), nullable=False),
    sa.Column('evidence_fingerprint', sa.String(), nullable=True),
    sa.Column('snapshot_artifact_id', sa.UUID(), nullable=False),
    sa.Column('webhook_raw_artifact_id', sa.UUID(), nullable=True),
    sa.Column('commits_raw_artifact_id', sa.UUID(), nullable=True),
    sa.Column('files_raw_artifact_id', sa.UUID(), nullable=True),
    sa.Column('dependency_subset_artifact_id', sa.UUID(), nullable=True),
    sa.Column('evidence_health_status', sa.String(), nullable=False),
    sa.Column('sync_integrity_status', sa.String(), nullable=False),
    sa.Column('evidence_consistency_status', sa.String(), nullable=False),
    sa.Column('evidence_truncated', sa.Boolean(), nullable=False),
    sa.Column('truncation_reason', sa.String(), nullable=True),
    sa.Column('unsafe_for_optimization', sa.Boolean(), nullable=False),
    sa.Column('evidence_generated_at', sa.DateTime(), nullable=True),
    sa.Column('evidence_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commits_raw_artifact_id'], ['raw_artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dependency_subset_artifact_id'], ['raw_artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['files_raw_artifact_id'], ['raw_artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_artifact_id'], ['raw_artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['webhook_raw_artifact_id'], ['raw_artifacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pull_request_snapshots_pull_request_id'), 'pull_request_snapshots', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_pull_request_snapshots_repository_id'), 'pull_request_snapshots', ['repository_id'], unique=False)
    op.create_table('pull_request_sync_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pull_request_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('github_installation_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sync_reason', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('commits_fetch_status', sa.String(), nullable=False),
    sa.Column('files_fetch_status', sa.String(), nullable=False),
    sa.Column('integrity_status', sa.String(), nullable=False),
    sa.Column('evidence_health_status', sa.String(), nullable=False),
    sa.Column('evidence_consistency_status', sa.String(), nullable=False),
    sa.Column('commits_count', sa.Integer(), nullable=False),
    sa.Column('changed_files_count', sa.Integer(), nullable=False),
    sa.Column('pagination_completed', sa.Boolean(), nullable=False),
    sa.Column('pages_received', sa.Integer(), nullable=False),
    sa.Column('snapshot_artifact_id', sa.UUID(), nullable=True),
    sa.Column('evidence_truncated', sa.Boolean(), nullable=False),
    sa.Column('truncation_reason', sa.String(), nullable=True),
    sa.Column('unsafe_for_optimization', sa.Boolean(), nullable=False),
    sa.Column('head_commit_sha', sa.String(), nullable=True),
    sa.Column('superseded_by_job_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_artifact_id'], ['raw_artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by_job_id'], ['pull_request_sync_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pull_request_sync_jobs_pull_request_id'), 'pull_request_sync_jobs', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_pull_request_sync_jobs_repository_id'), 'pull_request_sync_jobs', ['repository_id'], unique=False)
    op.add_column('recommendation_runs', sa.Column('pr_snapshot_id', sa.UUID(), nullable=True))
    op.add_column('recommendation_runs', sa.Column('pr_sync_job_id', sa.UUID(), nullable=True))
    op.add_column('recommendation_runs', sa.Column('evidence_health_status', sa.String(), nullable=True))
    op.add_column('recommendation_runs', sa.Column('recommendation_readiness_state', sa.String(), nullable=True))
    op.add_column('recommendation_runs', sa.Column('evidence_consistency_status', sa.String(), nullable=True))
    op.add_column('recommendation_runs', sa.Column('readiness_dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('recommendation_runs', sa.Column('evidence_fingerprint', sa.String(), nullable=True))
    op.create_foreign_key(None, 'recommendation_runs', 'pull_request_sync_jobs', ['pr_sync_job_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'recommendation_runs', 'pull_request_snapshots', ['pr_snapshot_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recommendation_runs', type_='foreignkey')
    op.drop_constraint(None, 'recommendation_runs', type_='foreignkey')
    op.drop_column('recommendation_runs', 'evidence_fingerprint')
    op.drop_column('recommendation_runs', 'readiness_dimensions')
    op.drop_column('recommendation_runs', 'evidence_consistency_status')
    op.drop_column('recommendation_runs', 'recommendation_readiness_state')
    op.drop_column('recommendation_runs', 'evidence_health_status')
    op.drop_column('recommendation_runs', 'pr_sync_job_id')
    op.drop_column('recommendation_runs', 'pr_snapshot_id')
    op.drop_index(op.f('ix_pull_request_sync_jobs_repository_id'), table_name='pull_request_sync_jobs')
    op.drop_index(op.f('ix_pull_request_sync_jobs_pull_request_id'), table_name='pull_request_sync_jobs')
    op.drop_table('pull_request_sync_jobs')
    op.drop_index(op.f('ix_pull_request_snapshots_repository_id'), table_name='pull_request_snapshots')
    op.drop_index(op.f('ix_pull_request_snapshots_pull_request_id'), table_name='pull_request_snapshots')
    op.drop_table('pull_request_snapshots')
    op.drop_index(op.f('ix_pull_request_commits_sha'), table_name='pull_request_commits')
    op.drop_index(op.f('ix_pull_request_commits_pull_request_id'), table_name='pull_request_commits')
    op.drop_table('pull_request_commits')
    op.drop_index(op.f('ix_pull_request_changed_files_pull_request_id'), table_name='pull_request_changed_files')
    op.drop_index(op.f('ix_pull_request_changed_files_file_path'), table_name='pull_request_changed_files')
    op.drop_table('pull_request_changed_files')
    op.drop_index(op.f('ix_pull_requests_repository_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_github_pr_id'), table_name='pull_requests')
    op.drop_table('pull_requests')
    # ### end Alembic commands ###
