"""add_label_to_acceptance_criteria

Revision ID: add_label_to_acceptance_criteria
Revises: j0k3l4m5n6o7
Create Date: 2026-06-10 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_label_to_acceptance_criteria'
down_revision: Union[str, Sequence[str], None] = 'j0k3l4m5n6o7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acceptance_criteria', sa.Column('label', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acceptance_criteria', 'label')
    # ### end Alembic commands ###
