"""add_governance_role_assignments

Revision ID: b1c2d3e4f5g6
Revises: a1b2c3d4e5f9
Create Date: 2026-06-18 09:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b1c2d3e4f5g6'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governance_role_assignments',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('repository_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('role', sa.Enum('GOVERNANCE_OWNER', 'POLICY_ADMIN', 'EXCEPTION_APPROVER', 'REPOSITORY_POLICY_MANAGER', 'GOVERNANCE_VIEWER', 'EXECUTIVE_VIEWER', 'AUDITOR', name='governancerole'), nullable=False),
    sa.Column('scope_type', sa.Enum('ORGANIZATION', 'REPOSITORY', name='scopetype'), nullable=False),
    sa.Column('assigned_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governance_role_assignments_organization_id'), 'governance_role_assignments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_governance_role_assignments_repository_id'), 'governance_role_assignments', ['repository_id'], unique=False)
    op.create_index(op.f('ix_governance_role_assignments_user_id'), 'governance_role_assignments', ['user_id'], unique=False)
    op.create_index(op.f('ix_governance_role_assignments_role'), 'governance_role_assignments', ['role'], unique=False)
    op.create_index(op.f('ix_governance_role_assignments_scope_type'), 'governance_role_assignments', ['scope_type'], unique=False)
    op.create_index(op.f('ix_governance_role_assignments_expires_at'), 'governance_role_assignments', ['expires_at'], unique=False)
    op.create_index(op.f('ix_governance_role_assignments_is_active'), 'governance_role_assignments', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_governance_role_assignments_is_active'), table_name='governance_role_assignments')
    op.drop_index(op.f('ix_governance_role_assignments_expires_at'), table_name='governance_role_assignments')
    op.drop_index(op.f('ix_governance_role_assignments_scope_type'), table_name='governance_role_assignments')
    op.drop_index(op.f('ix_governance_role_assignments_role'), table_name='governance_role_assignments')
    op.drop_index(op.f('ix_governance_role_assignments_user_id'), table_name='governance_role_assignments')
    op.drop_index(op.f('ix_governance_role_assignments_repository_id'), table_name='governance_role_assignments')
    op.drop_index(op.f('ix_governance_role_assignments_organization_id'), table_name='governance_role_assignments')
    op.drop_table('governance_role_assignments')
    # ### end Alembic commands ###
