"""add_journey_behavior_table

Revision ID: b2c4d6e8f0a2
Revises: a1b2c3d4e5f8
Create Date: 2026-06-01 14:35:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c4d6e8f0a2'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journey_behaviors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journey_id', sa.UUID(), nullable=False),
    sa.Column('behavior_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['behavior_id'], ['behaviors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journey_id', 'behavior_id', name='uq_journey_behavior')
    )
    op.create_index(op.f('ix_journey_behaviors_journey_id'), 'journey_behaviors', ['journey_id'], unique=False)
    op.create_index(op.f('ix_journey_behaviors_behavior_id'), 'journey_behaviors', ['behavior_id'], unique=False)
    op.create_index(op.f('ix_journey_behaviors_relationship_type'), 'journey_behaviors', ['relationship_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journey_behaviors_relationship_type'), table_name='journey_behaviors')
    op.drop_index(op.f('ix_journey_behaviors_behavior_id'), table_name='journey_behaviors')
    op.drop_index(op.f('ix_journey_behaviors_journey_id'), table_name='journey_behaviors')
    op.drop_table('journey_behaviors')
    # ### end Alembic commands ###
