"""add_behavior_evidence_table

Revision ID: c00a6b77841d
Revises: 834f57a4d970
Create Date: 2026-06-01 07:30:37.543678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00a6b77841d'
down_revision: Union[str, Sequence[str], None] = '834f57a4d970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavior_evidences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('behavior_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('source_path', sa.String(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['behavior_id'], ['behaviors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_evidences_behavior_id'), 'behavior_evidences', ['behavior_id'], unique=False)
    op.create_index('ix_behavior_evidences_behavior_type', 'behavior_evidences', ['behavior_id', 'evidence_type'], unique=False)
    op.create_index(op.f('ix_behavior_evidences_evidence_type'), 'behavior_evidences', ['evidence_type'], unique=False)
    op.create_index('ix_behavior_evidences_source_path', 'behavior_evidences', ['source_path'], unique=False)
    op.alter_column('behaviors', 'is_deleted',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=False,
               postgresql_using='is_deleted::boolean')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('behaviors', 'is_deleted',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index('ix_behavior_evidences_source_path', table_name='behavior_evidences')
    op.drop_index(op.f('ix_behavior_evidences_evidence_type'), table_name='behavior_evidences')
    op.drop_index('ix_behavior_evidences_behavior_type', table_name='behavior_evidences')
    op.drop_index(op.f('ix_behavior_evidences_behavior_id'), table_name='behavior_evidences')
    op.drop_table('behavior_evidences')
    # ### end Alembic commands ###
