"""add_journey_evidence_table

Revision ID: c3d5e7f9a1b3
Revises: b2c4d6e8f0a2
Create Date: 2026-06-01 14:39:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d5e7f9a1b3'
down_revision: Union[str, Sequence[str], None] = 'b2c4d6e8f0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journey_evidences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journey_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_evidences_journey_id'), 'journey_evidences', ['journey_id'], unique=False)
    op.create_index(op.f('ix_journey_evidences_evidence_type'), 'journey_evidences', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_journey_evidences_source'), 'journey_evidences', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journey_evidences_source'), table_name='journey_evidences')
    op.drop_index(op.f('ix_journey_evidences_evidence_type'), table_name='journey_evidences')
    op.drop_index(op.f('ix_journey_evidences_journey_id'), table_name='journey_evidences')
    op.drop_table('journey_evidences')
    # ### end Alembic commands ###
