"""add_phase_9_outcome_learning

Revision ID: c96a41da899b
Revises: cda47bebedda
Create Date: 2026-06-21 05:24:09.028825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c96a41da899b'
down_revision: Union[str, Sequence[str], None] = 'cda47bebedda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outcome_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('pull_request_id', sa.UUID(), nullable=True),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_run_id', sa.UUID(), nullable=True),
    sa.Column('github_pr_number', sa.Integer(), nullable=True),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_source', sa.String(), nullable=False),
    sa.Column('event_status', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('external_event_id', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommendation_run_id'], ['recommendation_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcome_events_event_type'), 'outcome_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_outcome_events_external_event_id'), 'outcome_events', ['external_event_id'], unique=False)
    op.create_index(op.f('ix_outcome_events_pipeline_run_id'), 'outcome_events', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_outcome_events_pull_request_id'), 'outcome_events', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_outcome_events_recommendation_run_id'), 'outcome_events', ['recommendation_run_id'], unique=False)
    op.create_index(op.f('ix_outcome_events_repository_id'), 'outcome_events', ['repository_id'], unique=False)
    op.create_index(op.f('ix_outcome_events_workspace_id'), 'outcome_events', ['workspace_id'], unique=False)
    
    op.create_table('recommendation_outcome_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_run_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('pull_request_id', sa.UUID(), nullable=True),
    sa.Column('github_pr_number', sa.Integer(), nullable=True),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('merged', sa.Boolean(), nullable=False),
    sa.Column('reverted', sa.Boolean(), nullable=False),
    sa.Column('deployment_failed', sa.Boolean(), nullable=False),
    sa.Column('incident_found', sa.Boolean(), nullable=False),
    sa.Column('bug_found', sa.Boolean(), nullable=False),
    sa.Column('regression_found', sa.Boolean(), nullable=False),
    sa.Column('missed_critical_test', sa.Boolean(), nullable=False),
    sa.Column('missed_high_test', sa.Boolean(), nullable=False),
    sa.Column('scope_accuracy', sa.String(), nullable=True),
    sa.Column('quality_gate_accuracy', sa.String(), nullable=True),
    sa.Column('learning_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommendation_run_id'], ['recommendation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_outcome_summaries_pipeline_run_id'), 'recommendation_outcome_summaries', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_recommendation_outcome_summaries_pull_request_id'), 'recommendation_outcome_summaries', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_recommendation_outcome_summaries_recommendation_run_id'), 'recommendation_outcome_summaries', ['recommendation_run_id'], unique=True)
    op.create_index(op.f('ix_recommendation_outcome_summaries_repository_id'), 'recommendation_outcome_summaries', ['repository_id'], unique=False)
    op.create_index(op.f('ix_recommendation_outcome_summaries_workspace_id'), 'recommendation_outcome_summaries', ['workspace_id'], unique=False)
    
    op.create_table('outcome_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outcome_event_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_run_id', sa.UUID(), nullable=False),
    sa.Column('label_type', sa.String(), nullable=False),
    sa.Column('label_value', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outcome_event_id'], ['outcome_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommendation_run_id'], ['recommendation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcome_labels_label_type'), 'outcome_labels', ['label_type'], unique=False)
    op.create_index(op.f('ix_outcome_labels_outcome_event_id'), 'outcome_labels', ['outcome_event_id'], unique=False)
    op.create_index(op.f('ix_outcome_labels_recommendation_run_id'), 'outcome_labels', ['recommendation_run_id'], unique=False)
    op.create_index(op.f('ix_outcome_labels_repository_id'), 'outcome_labels', ['repository_id'], unique=False)
    op.create_index(op.f('ix_outcome_labels_workspace_id'), 'outcome_labels', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outcome_labels_workspace_id'), table_name='outcome_labels')
    op.drop_index(op.f('ix_outcome_labels_repository_id'), table_name='outcome_labels')
    op.drop_index(op.f('ix_outcome_labels_recommendation_run_id'), table_name='outcome_labels')
    op.drop_index(op.f('ix_outcome_labels_outcome_event_id'), table_name='outcome_labels')
    op.drop_index(op.f('ix_outcome_labels_label_type'), table_name='outcome_labels')
    op.drop_table('outcome_labels')
    
    op.drop_index(op.f('ix_recommendation_outcome_summaries_workspace_id'), table_name='recommendation_outcome_summaries')
    op.drop_index(op.f('ix_recommendation_outcome_summaries_repository_id'), table_name='recommendation_outcome_summaries')
    op.drop_index(op.f('ix_recommendation_outcome_summaries_recommendation_run_id'), table_name='recommendation_outcome_summaries')
    op.drop_index(op.f('ix_recommendation_outcome_summaries_pull_request_id'), table_name='recommendation_outcome_summaries')
    op.drop_index(op.f('ix_recommendation_outcome_summaries_pipeline_run_id'), table_name='recommendation_outcome_summaries')
    op.drop_table('recommendation_outcome_summaries')
    
    op.drop_index(op.f('ix_outcome_events_workspace_id'), table_name='outcome_events')
    op.drop_index(op.f('ix_outcome_events_repository_id'), table_name='outcome_events')
    op.drop_index(op.f('ix_outcome_events_recommendation_run_id'), table_name='outcome_events')
    op.drop_index(op.f('ix_outcome_events_pull_request_id'), table_name='outcome_events')
    op.drop_index(op.f('ix_outcome_events_pipeline_run_id'), table_name='outcome_events')
    op.drop_index(op.f('ix_outcome_events_external_event_id'), table_name='outcome_events')
    op.drop_index(op.f('ix_outcome_events_event_type'), table_name='outcome_events')
    op.drop_table('outcome_events')
    # ### end Alembic commands ###
