"""add_latest_comment_body_hash

Revision ID: d2218e8e86aa
Revises: 1e7e70950de3
Create Date: 2026-05-23 21:23:20.567366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2218e8e86aa'
down_revision: Union[str, Sequence[str], None] = '1e7e70950de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_request_comment_states', sa.Column('latest_comment_body_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pull_request_comment_states', 'latest_comment_body_hash')
    # ### end Alembic commands ###
