"""add_journey_step_table

Revision ID: d4e6f8a2b4c5
Revises: c3d5e7f9a1b3
Create Date: 2026-06-01 14:42:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e6f8a2b4c5'
down_revision: Union[str, Sequence[str], None] = 'c3d5e7f9a1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journey_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journey_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(), nullable=False),
    sa.Column('behavior_id', sa.UUID(), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['behavior_id'], ['behaviors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journey_id', 'step_order', name='uq_journey_step_order')
    )
    op.create_index(op.f('ix_journey_steps_journey_id'), 'journey_steps', ['journey_id'], unique=False)
    op.create_index(op.f('ix_journey_steps_step_order'), 'journey_steps', ['step_order'], unique=False)
    op.create_index(op.f('ix_journey_steps_behavior_id'), 'journey_steps', ['behavior_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journey_steps_behavior_id'), table_name='journey_steps')
    op.drop_index(op.f('ix_journey_steps_step_order'), table_name='journey_steps')
    op.drop_index(op.f('ix_journey_steps_journey_id'), table_name='journey_steps')
    op.drop_table('journey_steps')
    # ### end Alembic commands ###
