"""Add architecture_nodes table for repository graph representation

Revision ID: d9187d4b38db
Revises: ae9831957a5f
Create Date: 2026-06-01 22:50:33.802996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9187d4b38db'
down_revision: Union[str, Sequence[str], None] = 'ae9831957a5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('architecture_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('node_type', sa.Enum('FILE', 'ROUTE', 'PAGE', 'COMPONENT', 'SERVICE', 'MODULE', 'API_ENDPOINT', 'DATABASE_MODEL', 'CONFIG', 'TEST', 'UNKNOWN', name='architecture_node_type'), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('normalized_path', sa.Text(), nullable=False),
    sa.Column('module_name', sa.String(length=255), nullable=True),
    sa.Column('framework_hint', sa.String(length=100), nullable=True),
    sa.Column('layer', sa.Enum('UI', 'API', 'DOMAIN', 'DATA', 'INFRA', 'TEST', 'CONFIG', 'UNKNOWN', name='architecture_layer'), nullable=False),
    sa.Column('node_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_architecture_nodes_layer'), 'architecture_nodes', ['layer'], unique=False)
    op.create_index('ix_architecture_nodes_module', 'architecture_nodes', ['repository_id', 'module_name'], unique=False)
    op.create_index(op.f('ix_architecture_nodes_module_name'), 'architecture_nodes', ['module_name'], unique=False)
    op.create_index(op.f('ix_architecture_nodes_node_type'), 'architecture_nodes', ['node_type'], unique=False)
    op.create_index(op.f('ix_architecture_nodes_normalized_path'), 'architecture_nodes', ['normalized_path'], unique=False)
    op.create_index(op.f('ix_architecture_nodes_path'), 'architecture_nodes', ['path'], unique=False)
    op.create_index('ix_architecture_nodes_repo_path', 'architecture_nodes', ['repository_id', 'normalized_path'], unique=True)
    op.create_index('ix_architecture_nodes_repo_type_layer', 'architecture_nodes', ['repository_id', 'node_type', 'layer'], unique=False)
    op.create_index(op.f('ix_architecture_nodes_repository_id'), 'architecture_nodes', ['repository_id'], unique=False)
    op.drop_constraint(op.f('acceptance_criteria_repository_id_fkey'), 'acceptance_criteria', type_='foreignkey')
    op.drop_constraint(op.f('acceptance_criteria_pull_request_id_fkey'), 'acceptance_criteria', type_='foreignkey')
    op.create_foreign_key(None, 'acceptance_criteria', 'repositories', ['repository_id'], ['id'])
    op.create_foreign_key(None, 'acceptance_criteria', 'pull_requests', ['pull_request_id'], ['id'])
    op.alter_column('behavior_impact_items', 'impact_reason',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('behavior_impact_items', 'source_signals',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('behavior_impact_items', 'impacted_files',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('behavior_impact_items', 'affected_scenarios',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('behavior_impact_runs', 'impact_summary',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('behavior_scenario_coverages', 'reason',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('behavior_scenario_coverages', 'existing_tests',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('behavior_scenario_coverages', 'suggested_scenarios',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('behavior_scenario_coverages', 'coverage_files',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('journey_intelligence_snapshots', 'affected_journeys',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('journey_intelligence_snapshots', 'affected_behaviors',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('journey_intelligence_snapshots', 'journey_risks',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('journey_intelligence_snapshots', 'coverage_gaps',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('journey_intelligence_snapshots', 'testing_scope',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('journey_relationships', 'impact_analysis',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('journey_relationships', 'impact_analysis',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('journey_intelligence_snapshots', 'testing_scope',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('journey_intelligence_snapshots', 'coverage_gaps',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('journey_intelligence_snapshots', 'journey_risks',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('journey_intelligence_snapshots', 'affected_behaviors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('journey_intelligence_snapshots', 'affected_journeys',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('behavior_scenario_coverages', 'coverage_files',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('behavior_scenario_coverages', 'suggested_scenarios',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('behavior_scenario_coverages', 'existing_tests',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('behavior_scenario_coverages', 'reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('behavior_impact_runs', 'impact_summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('behavior_impact_items', 'affected_scenarios',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('behavior_impact_items', 'impacted_files',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('behavior_impact_items', 'source_signals',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('behavior_impact_items', 'impact_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'acceptance_criteria', type_='foreignkey')
    op.drop_constraint(None, 'acceptance_criteria', type_='foreignkey')
    op.create_foreign_key(op.f('acceptance_criteria_pull_request_id_fkey'), 'acceptance_criteria', 'pull_requests', ['pull_request_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('acceptance_criteria_repository_id_fkey'), 'acceptance_criteria', 'repositories', ['repository_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_architecture_nodes_repository_id'), table_name='architecture_nodes')
    op.drop_index('ix_architecture_nodes_repo_type_layer', table_name='architecture_nodes')
    op.drop_index('ix_architecture_nodes_repo_path', table_name='architecture_nodes')
    op.drop_index(op.f('ix_architecture_nodes_path'), table_name='architecture_nodes')
    op.drop_index(op.f('ix_architecture_nodes_normalized_path'), table_name='architecture_nodes')
    op.drop_index(op.f('ix_architecture_nodes_node_type'), table_name='architecture_nodes')
    op.drop_index(op.f('ix_architecture_nodes_module_name'), table_name='architecture_nodes')
    op.drop_index('ix_architecture_nodes_module', table_name='architecture_nodes')
    op.drop_index(op.f('ix_architecture_nodes_layer'), table_name='architecture_nodes')
    op.drop_table('architecture_nodes')
    # ### end Alembic commands ###
