"""refine_phase4_fragility_memory

Revision ID: ddc80c667eb9
Revises: 7d8b28c4a68b
Create Date: 2026-05-23 14:25:10.327144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddc80c667eb9'
down_revision: Union[str, Sequence[str], None] = '7d8b28c4a68b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fragility_patterns', sa.Column('title', sa.String(), nullable=False))
    op.add_column('fragility_patterns', sa.Column('pattern_hash', sa.String(), nullable=False))
    op.add_column('fragility_patterns', sa.Column('replayable_evidence_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index(op.f('ix_fragility_patterns_pattern_hash'), 'fragility_patterns', ['pattern_hash'], unique=False)
    op.add_column('fragility_snapshots', sa.Column('snapshot_hash', sa.String(), nullable=False))
    op.add_column('fragility_snapshots', sa.Column('generated_at', sa.DateTime(), nullable=False))
    op.add_column('fragility_snapshots', sa.Column('total_patterns', sa.Integer(), nullable=False))
    op.add_column('fragility_snapshots', sa.Column('active_patterns', sa.Integer(), nullable=False))
    op.add_column('fragility_snapshots', sa.Column('stale_patterns', sa.Integer(), nullable=False))
    op.add_column('fragility_snapshots', sa.Column('snapshot_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index(op.f('ix_fragility_snapshots_snapshot_hash'), 'fragility_snapshots', ['snapshot_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fragility_snapshots_snapshot_hash'), table_name='fragility_snapshots')
    op.drop_column('fragility_snapshots', 'snapshot_metadata')
    op.drop_column('fragility_snapshots', 'stale_patterns')
    op.drop_column('fragility_snapshots', 'active_patterns')
    op.drop_column('fragility_snapshots', 'total_patterns')
    op.drop_column('fragility_snapshots', 'generated_at')
    op.drop_column('fragility_snapshots', 'snapshot_hash')
    op.drop_index(op.f('ix_fragility_patterns_pattern_hash'), table_name='fragility_patterns')
    op.drop_column('fragility_patterns', 'replayable_evidence_snapshot')
    op.drop_column('fragility_patterns', 'pattern_hash')
    op.drop_column('fragility_patterns', 'title')
    # ### end Alembic commands ###
