"""add_repository_semantic_entry_table

Revision ID: e43aee5759fe
Revises: 738169b4af18
Create Date: 2026-06-01 13:54:32.153015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e43aee5759fe'
down_revision: Union[str, Sequence[str], None] = '738169b4af18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_semantic_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('normalized_tokens', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('entry_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_semantic_entries_confidence'), 'repository_semantic_entries', ['confidence'], unique=False)
    op.create_index(op.f('ix_repository_semantic_entries_entry_type'), 'repository_semantic_entries', ['entry_type'], unique=False)
    op.create_index(op.f('ix_repository_semantic_entries_path'), 'repository_semantic_entries', ['path'], unique=False)
    op.create_index(op.f('ix_repository_semantic_entries_repository_id'), 'repository_semantic_entries', ['repository_id'], unique=False)
    op.create_index('ix_semantic_entries_repo_type', 'repository_semantic_entries', ['repository_id', 'entry_type'], unique=False)
    op.create_index('ix_semantic_entries_tokens', 'repository_semantic_entries', ['normalized_tokens'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_semantic_entries_tokens', table_name='repository_semantic_entries', postgresql_using='gin')
    op.drop_index('ix_semantic_entries_repo_type', table_name='repository_semantic_entries')
    op.drop_index(op.f('ix_repository_semantic_entries_repository_id'), table_name='repository_semantic_entries')
    op.drop_index(op.f('ix_repository_semantic_entries_path'), table_name='repository_semantic_entries')
    op.drop_index(op.f('ix_repository_semantic_entries_entry_type'), table_name='repository_semantic_entries')
    op.drop_index(op.f('ix_repository_semantic_entries_confidence'), table_name='repository_semantic_entries')
    op.drop_table('repository_semantic_entries')
    # ### end Alembic commands ###
