"""add_journey_intelligence_snapshot_table

Revision ID: e5f8a9b0c1d2
Revises: d4e6f8a2b4c5
Create Date: 2026-06-01 15:04:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f8a9b0c1d2'
down_revision: Union[str, Sequence[str], None] = 'd4e6f8a2b4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journey_intelligence_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_run_id', sa.UUID(), nullable=False),
    sa.Column('affected_journeys', sa.JSON(), nullable=False),
    sa.Column('affected_behaviors', sa.JSON(), nullable=False),
    sa.Column('journey_risks', sa.JSON(), nullable=False),
    sa.Column('coverage_gaps', sa.JSON(), nullable=False),
    sa.Column('testing_scope', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_run_id'], ['recommendation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_intelligence_snapshots_recommendation_run_id'), 'journey_intelligence_snapshots', ['recommendation_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journey_intelligence_snapshots_recommendation_run_id'), table_name='journey_intelligence_snapshots')
    op.drop_table('journey_intelligence_snapshots')
    # ### end Alembic commands ###
