"""add_flaky_test_and_jobs_schema

Revision ID: f147c303de7f
Revises: b1cb35183ccb
Create Date: 2026-05-22 21:22:29.531107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f147c303de7f'
down_revision: Union[str, Sequence[str], None] = 'b1cb35183ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flaky_recalculation_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('recalculation_scope', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flaky_recalculation_jobs_repository_id'), 'flaky_recalculation_jobs', ['repository_id'], unique=False)
    op.create_table('flaky_test_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.UUID(), nullable=False),
    sa.Column('execution_environment', sa.String(), nullable=True),
    sa.Column('runner_type', sa.String(), nullable=True),
    sa.Column('ci_provider', sa.String(), nullable=True),
    sa.Column('test_framework', sa.String(), nullable=True),
    sa.Column('failure_rate', sa.Float(), nullable=False),
    sa.Column('recent_failure_rate', sa.Float(), nullable=False),
    sa.Column('instability_score', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('confidence_level', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.Column('stability_recovered_at', sa.DateTime(), nullable=True),
    sa.Column('last_recalculated_at', sa.DateTime(), nullable=True),
    sa.Column('stale_profile', sa.Boolean(), nullable=False),
    sa.Column('failure_mode_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quarantined_at', sa.DateTime(), nullable=True),
    sa.Column('quarantine_reason', sa.String(), nullable=True),
    sa.Column('quarantine_review_due_at', sa.DateTime(), nullable=True),
    sa.Column('quarantined_by', sa.String(), nullable=True),
    sa.Column('flakiness_calculation_version', sa.String(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flaky_test_profiles_repository_id'), 'flaky_test_profiles', ['repository_id'], unique=False)
    op.create_index(op.f('ix_flaky_test_profiles_test_case_id'), 'flaky_test_profiles', ['test_case_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flaky_test_profiles_test_case_id'), table_name='flaky_test_profiles')
    op.drop_index(op.f('ix_flaky_test_profiles_repository_id'), table_name='flaky_test_profiles')
    op.drop_table('flaky_test_profiles')
    op.drop_index(op.f('ix_flaky_recalculation_jobs_repository_id'), table_name='flaky_recalculation_jobs')
    op.drop_table('flaky_recalculation_jobs')
    # ### end Alembic commands ###
