"""add_journey_relationship_table

Revision ID: f6g9b0c1d2e3
Revises: e5f8a9b0c1d2
Create Date: 2026-06-01 15:07:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6g9b0c1d2e3'
down_revision: Union[str, Sequence[str], None] = 'e5f8a9b0c1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journey_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_journey_id', sa.UUID(), nullable=False),
    sa.Column('target_journey_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('evidence_source', sa.String(), nullable=False),
    sa.Column('evidence_excerpt', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('relationship_description', sa.String(), nullable=True),
    sa.Column('impact_analysis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_journey_id'], ['journeys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_journey_id'], ['journeys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_relationships_source_journey_id'), 'journey_relationships', ['source_journey_id'], unique=False)
    op.create_index(op.f('ix_journey_relationships_target_journey_id'), 'journey_relationships', ['target_journey_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journey_relationships_target_journey_id'), table_name='journey_relationships')
    op.drop_index(op.f('ix_journey_relationships_source_journey_id'), table_name='journey_relationships')
    op.drop_table('journey_relationships')
    # ### end Alembic commands ###
