"""add_behavior_impact_runs_and_items_tables

Revision ID: h8i1c2d3e4f5
Revises: f6g9b0c1d2e3
Create Date: 2026-06-01 15:29:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'h8i1c2d3e4f5'
down_revision: Union[str, Sequence[str], None] = 'f6g9b0c1d2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavior_impact_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('pull_request_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_run_id', sa.UUID(), nullable=True),
    sa.Column('impact_summary', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_run_id'], ['recommendation_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_impact_runs_recommendation_run_id'), 'behavior_impact_runs', ['recommendation_run_id'], unique=False)
    op.create_index(op.f('ix_behavior_impact_runs_repository_id'), 'behavior_impact_runs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_behavior_impact_runs_pull_request_id'), 'behavior_impact_runs', ['pull_request_id'], unique=False)

    op.create_table('behavior_impact_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('behavior_impact_run_id', sa.UUID(), nullable=False),
    sa.Column('behavior_id', sa.UUID(), nullable=False),
    sa.Column('journey_id', sa.UUID(), nullable=True),
    sa.Column('impact_level', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('impact_reason', sa.String(), nullable=True),
    sa.Column('source_signals', sa.JSON(), nullable=False),
    sa.Column('impacted_files', sa.JSON(), nullable=False),
    sa.Column('affected_scenarios', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['behavior_impact_run_id'], ['behavior_impact_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['behavior_id'], ['behaviors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_impact_items_behavior_impact_run_id'), 'behavior_impact_items', ['behavior_impact_run_id'], unique=False)
    op.create_index(op.f('ix_behavior_impact_items_behavior_id'), 'behavior_impact_items', ['behavior_id'], unique=False)
    op.create_index(op.f('ix_behavior_impact_items_journey_id'), 'behavior_impact_items', ['journey_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_behavior_impact_items_journey_id'), table_name='behavior_impact_items')
    op.drop_index(op.f('ix_behavior_impact_items_behavior_id'), table_name='behavior_impact_items')
    op.drop_index(op.f('ix_behavior_impact_items_behavior_impact_run_id'), table_name='behavior_impact_items')
    op.drop_table('behavior_impact_items')

    op.drop_index(op.f('ix_behavior_impact_runs_pull_request_id'), table_name='behavior_impact_runs')
    op.drop_index(op.f('ix_behavior_impact_runs_repository_id'), table_name='behavior_impact_runs')
    op.drop_index(op.f('ix_behavior_impact_runs_recommendation_run_id'), table_name='behavior_impact_runs')
    op.drop_table('behavior_impact_runs')
    # ### end Alembic commands ###
