"""add_behavior_scenario_coverages_table

Revision ID: i9j2c3d4e5f6
Revises: h8i1c2d3e4f5
Create Date: 2026-06-01 15:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'i9j2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = 'h8i1c2d3e4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavior_scenario_coverages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('behavior_id', sa.UUID(), nullable=False),
    sa.Column('behavior_scenario_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_run_id', sa.UUID(), nullable=True),
    sa.Column('coverage_status', sa.String(), nullable=False),
    sa.Column('current_pr_execution_status', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('existing_tests', sa.JSON(), nullable=False),
    sa.Column('suggested_scenarios', sa.JSON(), nullable=False),
    sa.Column('coverage_files', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_run_id'], ['recommendation_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['behavior_id'], ['behaviors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['behavior_scenario_id'], ['behavior_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_scenario_coverages_repository_id'), 'behavior_scenario_coverages', ['repository_id'], unique=False)
    op.create_index(op.f('ix_behavior_scenario_coverages_behavior_id'), 'behavior_scenario_coverages', ['behavior_id'], unique=False)
    op.create_index(op.f('ix_behavior_scenario_coverages_behavior_scenario_id'), 'behavior_scenario_coverages', ['behavior_scenario_id'], unique=False)
    op.create_index(op.f('ix_behavior_scenario_coverages_recommendation_run_id'), 'behavior_scenario_coverages', ['recommendation_run_id'], unique=False)
    op.create_index(op.f('ix_behavior_scenario_coverages_coverage_status'), 'behavior_scenario_coverages', ['coverage_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_behavior_scenario_coverages_coverage_status'), table_name='behavior_scenario_coverages')
    op.drop_index(op.f('ix_behavior_scenario_coverages_recommendation_run_id'), table_name='behavior_scenario_coverages')
    op.drop_index(op.f('ix_behavior_scenario_coverages_behavior_scenario_id'), table_name='behavior_scenario_coverages')
    op.drop_index(op.f('ix_behavior_scenario_coverages_behavior_id'), table_name='behavior_scenario_coverages')
    op.drop_index(op.f('ix_behavior_scenario_coverages_repository_id'), table_name='behavior_scenario_coverages')
    op.drop_table('behavior_scenario_coverages')
    # ### end Alembic commands ###
