"""add_acceptance_criteria_table

Revision ID: j0k3l4m5n6o7
Revises: i9j2c3d4e5f6
Create Date: 2026-06-01 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'j0k3l4m5n6o7'
down_revision: Union[str, Sequence[str], None] = 'i9j2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acceptance_criteria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('pull_request_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('normalized_key', sa.String(length=500), nullable=False),
    sa.Column('criterion_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_excerpt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acceptance_criteria_repository_id'), 'acceptance_criteria', ['repository_id'], unique=False)
    op.create_index(op.f('ix_acceptance_criteria_pull_request_id'), 'acceptance_criteria', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_acceptance_criteria_normalized_key'), 'acceptance_criteria', ['normalized_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acceptance_criteria_normalized_key'), table_name='acceptance_criteria')
    op.drop_index(op.f('ix_acceptance_criteria_pull_request_id'), table_name='acceptance_criteria')
    op.drop_index(op.f('ix_acceptance_criteria_repository_id'), table_name='acceptance_criteria')
    op.drop_table('acceptance_criteria')
    # ### end Alembic commands ###
