"""add_business_behavior_mapping_table

Revision ID: k1l2m3n4o5p6
Revises: j0k3l4m5n6o7
Create Date: 2026-06-01 16:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'k1l2m3n4o5p6'
down_revision: Union[str, Sequence[str], None] = 'j0k3l4m5n6o7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_behavior_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('acceptance_criterion_id', sa.UUID(), nullable=True),
    sa.Column('behavior_id', sa.UUID(), nullable=False),
    sa.Column('behavior_scenario_id', sa.UUID(), nullable=True),
    sa.Column('journey_id', sa.UUID(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('matched_terms', postgresql.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_candidate_missing_scenario', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acceptance_criterion_id'], ['acceptance_criteria.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['behavior_id'], ['behaviors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['behavior_scenario_id'], ['behavior_scenarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_behavior_mappings_acceptance_criterion_id'), 'business_behavior_mappings', ['acceptance_criterion_id'], unique=False)
    op.create_index(op.f('ix_business_behavior_mappings_behavior_id'), 'business_behavior_mappings', ['behavior_id'], unique=False)
    op.create_index(op.f('ix_business_behavior_mappings_behavior_scenario_id'), 'business_behavior_mappings', ['behavior_scenario_id'], unique=False)
    op.create_index(op.f('ix_business_behavior_mappings_journey_id'), 'business_behavior_mappings', ['journey_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_behavior_mappings_journey_id'), table_name='business_behavior_mappings')
    op.drop_index(op.f('ix_business_behavior_mappings_behavior_scenario_id'), table_name='business_behavior_mappings')
    op.drop_index(op.f('ix_business_behavior_mappings_behavior_id'), table_name='business_behavior_mappings')
    op.drop_index(op.f('ix_business_behavior_mappings_acceptance_criterion_id'), table_name='business_behavior_mappings')
    op.drop_table('business_behavior_mappings')
    # ### end Alembic commands ###
