"""add_expected_behavior_scenario_table

Revision ID: l2m3n4o5p6q7
Revises: k1l2m3n4o5p6
Create Date: 2026-06-01 17:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'l2m3n4o5p6q7'
down_revision: Union[str, Sequence[str], None] = 'k1l2m3n4o5p6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expected_behavior_scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('behavior_id', sa.UUID(), nullable=True),
    sa.Column('journey_id', sa.UUID(), nullable=True),
    sa.Column('acceptance_criterion_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('testing_type', sa.String(length=50), nullable=False),
    sa.Column('scenario_type', sa.String(length=50), nullable=False),
    sa.Column('preconditions', postgresql.JSON(), nullable=False),
    sa.Column('test_data', postgresql.JSON(), nullable=True),
    sa.Column('steps', postgresql.JSON(), nullable=False),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('matches_existing_test', sa.String(), nullable=False),
    sa.Column('recommendation_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acceptance_criterion_id'], ['acceptance_criteria.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['behavior_id'], ['behaviors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommendation_run_id'], ['recommendation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expected_behavior_scenarios_acceptance_criterion_id'), 'expected_behavior_scenarios', ['acceptance_criterion_id'], unique=False)
    op.create_index(op.f('ix_expected_behavior_scenarios_behavior_id'), 'expected_behavior_scenarios', ['behavior_id'], unique=False)
    op.create_index(op.f('ix_expected_behavior_scenarios_journey_id'), 'expected_behavior_scenarios', ['journey_id'], unique=False)
    op.create_index(op.f('ix_expected_behavior_scenarios_recommendation_run_id'), 'expected_behavior_scenarios', ['recommendation_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expected_behavior_scenarios_recommendation_run_id'), table_name='expected_behavior_scenarios')
    op.drop_index(op.f('ix_expected_behavior_scenarios_journey_id'), table_name='expected_behavior_scenarios')
    op.drop_index(op.f('ix_expected_behavior_scenarios_behavior_id'), table_name='expected_behavior_scenarios')
    op.drop_index(op.f('ix_expected_behavior_scenarios_acceptance_criterion_id'), table_name='expected_behavior_scenarios')
    op.drop_table('expected_behavior_scenarios')
    # ### end Alembic commands ###
