"""
One-time cleanup: removes mock test data written to the 
live database by unit tests that used SessionLocal directly.
"""
import sys
from app.db.session import SessionLocal
from app.models import (
    AcceptanceCriterion, TestCase, TestResult, 
    TestRun, FileTestLink
)
from app.models.test_coverage_link import TestCoverageLink
from sqlalchemy import or_

def cleanup():
    db = SessionLocal()
    try:
        # ---- IDENTIFY MOCK TEST CASES ----
        # 1. Test cases generated by test fixtures with "test_password_validation_" or "Password validation requirement"
        # 2. Test cases with UUIDs or 'test' as canonical_identity_hash
        tc_query = db.query(TestCase).filter(
            or_(
                TestCase.test_name.like('Password validation requirement%'),
                TestCase.stable_identity.like('test_password_validation%'),
                TestCase.test_name.like('test_password_validation%'),
                TestCase.canonical_identity_hash.like('%-%'),
                TestCase.canonical_identity_hash == 'test'
            )
        )
        
        mock_cases = tc_query.all()
        mock_tc_ids = [tc.id for tc in mock_cases]
        mock_tc_stable_ids = [tc.stable_identity for tc in mock_cases]
        mock_tc_count = len(mock_tc_ids)
        
        # ---- IDENTIFY MOCK ACS ----
        ac_query = db.query(AcceptanceCriterion).filter(
            or_(
                AcceptanceCriterion.label.like('Password validation requirement%'),
                AcceptanceCriterion.text.like('Password validation requirement%')
            )
        )
        mock_ac_count = ac_query.count()
        
        print(f"[BEFORE] Mock ACs: {mock_ac_count}")
        print(f"[BEFORE] Mock TestCases: {mock_tc_count}")
        
        if mock_ac_count == 0 and mock_tc_count == 0:
            print("[INFO] No mock data found. Nothing to clean.")
            
            # Still print total counts as expected by the script verification
            total_ac = db.query(AcceptanceCriterion).count()
            total_tc = db.query(TestCase).count()
            print(f"[TOTAL] ACs in database: {total_ac}")
            print(f"[TOTAL] TestCases in database: {total_tc}")
            return
        
        # ---- DELETE IN ORDER ----
        if mock_tc_ids:
            deleted_results = db.query(TestResult).filter(
                TestResult.test_case_id.in_(mock_tc_ids)
            ).delete(synchronize_session=False)
            print(f"[DELETE] TestResults: {deleted_results}")
            
            deleted_links = db.query(FileTestLink).filter(
                FileTestLink.test_case_id.in_(mock_tc_ids)
            ).delete(synchronize_session=False)
            print(f"[DELETE] FileTestLinks: {deleted_links}")
            
            deleted_coverage_links = db.query(TestCoverageLink).filter(
                TestCoverageLink.test_identifier.in_(mock_tc_stable_ids)
            ).delete(synchronize_session=False)
            print(f"[DELETE] TestCoverageLinks: {deleted_coverage_links}")
            
            deleted_cases = db.query(TestCase).filter(
                TestCase.id.in_(mock_tc_ids)
            ).delete(synchronize_session=False)
            print(f"[DELETE] TestCases: {deleted_cases}")
        
        deleted_acs = ac_query.delete(synchronize_session=False)
        print(f"[DELETE] AcceptanceCriteria: {deleted_acs}")
        
        db.commit()
        
        # ---- COUNT AFTER ----
        after_ac = db.query(AcceptanceCriterion).filter(
            or_(
                AcceptanceCriterion.label.like('Password validation requirement%'),
                AcceptanceCriterion.text.like('Password validation requirement%')
            )
        ).count()
        
        after_tc = db.query(TestCase).filter(
            or_(
                TestCase.test_name.like('Password validation requirement%'),
                TestCase.stable_identity.like('test_password_validation%'),
                TestCase.test_name.like('test_password_validation%'),
                TestCase.canonical_identity_hash.like('%-%'),
                TestCase.canonical_identity_hash == 'test'
            )
        ).count()
        
        print(f"[AFTER] Mock ACs remaining: {after_ac}")
        print(f"[AFTER] Mock TestCases remaining: {after_tc}")
        
        total_ac = db.query(AcceptanceCriterion).count()
        total_tc = db.query(TestCase).count()
        print(f"[TOTAL] ACs in database: {total_ac}")
        print(f"[TOTAL] TestCases in database: {total_tc}")
        print("[DONE] Cleanup complete.")
        
    except Exception as e:
        db.rollback()
        print(f"[ERROR] {e}")
        raise
    finally:
        db.close()

if __name__ == "__main__":
    cleanup()
